<?php $catIds = Mage::registry('current_cateogries'); ?>
<?php
$company = Mage::registry('current_company');
$cats = Mage::getResourceModel('edm/company_category_collection')
				->addFieldToFilter('company_id',$company->getId());	
$cats->getSelect()->join(array('p'=>'edm_product_category'),'p.category_id=main_table.category_id',array('level','name'));
$catOldIds = array();
$catNames = array();
$subCatNames = array();
foreach ($cats as $_cat) {
	array_push($catOldIds,$_cat->getCategoryId());
	
	if ($_cat->getLevel()==1) {
		array_push($catNames,$_cat->getName());
	} else if ($_cat->getLevel()==2) {
		array_push($subCatNames,$_cat->getName());
	}
}

?>
<div class="inner">
<?php foreach ($catIds as $_id): ?>
<?php $_item = Mage::getModel('edm/product_category')->load($_id); ?>
	<?php if ($_item->getId()): ?>
	<dl>
		<dt><?php echo $_item->getName(); ?></dt>
		<?php foreach ($_item->getChildren() as $_child): ?>
		<dd data="<?php echo $_child->getId(); ?>" class="select-category <?php if(in_array($_child->getId(),$catOldIds)): ?> selected <?php endif; ?>"><?php echo $_child->getName(); ?></dd>
		<?php endforeach; ?>
	</dl>
	<?php endif; ?>
<?php endforeach; ?>
</div>

<div class="clr"></div>
<div class="btn-box mt20 mb20">
<button class="button" type="button" id="select_subcat_btn" onclick="saveStep1()">确认 &amp; 保存</button>
</div>
