<div class="c-box">
	<div class="content-header">
		<table>
			<tr>
				<td><?php echo $this->getHeaderHtml() ?></td>
				<td class="form-buttons"><?php echo $this->getButtonsHtml('header') ?></td>
			</tr>
		</table>
		<div id="messages">
            <?php echo $this->getMessagesBlock()->toHtml() ?>
        </div>
    </div>
    <table cellspacing="6" width="100%">
        <tr>  
            <td>
                <div class="entry-edit" style="margin:0;">
					
					<div>
						<?php echo $this->getFormInitScripts() ?>
						
						<?php echo $this->getFormHtml() ?>
						<?php if ($this->hasFooterButtons()): ?>
						    <div class="content-footer">
						        <p class="form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
						    </div>
						<?php endif; ?>
						<script type="text/javascript">
						    editForm = new mioForm('edit_form', '<?php echo $this->getValidationUrl() ?>');
						</script>
						<?php echo $this->getFormScripts() ?>
					</div>
				</div>
			</td>
		</tr>
	</table>
</div>
