<?php $company = Mage::registry('current_company'); ?>
<?php $user = Mage::getSingleton('admin/session')->getUser(); ?>

<div class="inner"  id="box_email">
	<input type="hidden" id="form_key" value="<?php echo $this->getFormKey(); ?>" />
	<input type="hidden" id="client_id" value="" />
	<input type="hidden" id="switch_url" value='<?php echo $this->getUrl('adminhtml/ajax_client/switch',array('isAjax'=>true)); ?>' />
	<input type="hidden" id="config_url" value='<?php echo $this->getUrl('adminhtml/ajax_client/config',array('isAjax'=>true)); ?>' />
	<input type="hidden" id="config_save_url" value='<?php echo $this->getUrl('adminhtml/ajax_client/configsave',array('isAjax'=>true)); ?>' />
	<div class="">
	   	<div class="btns mb5">
	   		<ul class="mode-toggle f-left">
    			<li class="active " id="mode-highlight" onclick="toggleModel(0)"><a href="javascript:;">高亮模式</a></li>
    			<li class="" id="mode-preview" onclick="toggleModel(1)"><a href="javascript:;">预览模式</a></li>
    		</ul>

	   		<!--<button class="btn btn_grey f-left mr5" class="preview_email_btn" type="button" onclick="previewEmail()" style="">预览</button>-->
	   		<button class="btn btn_grey f-left mr5" class="save_email_btn" type="button" onclick="saveasTemplateProcess()" style="">存为模版</button>
	   		<button class="btn f-left mr5" class="send_email_btn" type="button" onclick="checkEmail()" style="">发送邮件</button>
	   		<div class="clr"></div>
	   	</div>
    	<div class="field mb5">
			<label class="tit">选择模版：</label>
			<div class="multi fields">
				<div class="a-left">
					<?php $templates = Mage::getResourceModel('edm/company_template_collection')
						->addFieldToFilter('template_company',$company->getId()); ?>
					<select name="email_template" id="email_template" class="ipt wp75" onchange="renderEmail();">
					<?php foreach ($templates as $_template): ?>
						<option value="<?php echo $_template->getId(); ?>"><?php echo $_template->getData('template_name'); ?></option>
					<?php endforeach; ?>
					</select>
					
				</div>
				<div class="clr"></div>
			</div>
		</div>
    	<div class="field">
			<label class="tit">收件人：</label>
			<div class="multi fields">
				<div class="wp100">
					<input type="text" name="email_to" id="email_to" class="ipt wp75 f-left"/>
					<div class="wp20">
					
					</div>
					<div class="clr"></div>
				</div>
			</div>
		</div>
		<div class="field">
			<label class="tit">发件人：</label>
			<div class="selection fields a-left">
				<div class=" f-left mr10">
					<span class="selected" id="email_from" data-from="<?php echo $company->getData('contact_person') ?>" data="<?php echo $company->getData('contact_email') ?>"><?php echo $company->getData('contact_person') ?>&lt;<?php echo $company->getData('contact_email') ?>&gt;</span>
					<i class="icon icon-ad"></i>
				</div>
				<div class=" f-left">
					<div class="">
						<input type="checkbox" name="cc_me" id="cc_me" /> 给我CC
					</div>
				</div>
				<ul class="dropdown" style="display:none">
					<li></li>
				</ul>
				<div class="clr"></div>
			</div>
			
		</div>
		<div class="field mb15">
			<label class="tit">邮件主题：</label>
			<div class="fields">
				<div class="wp100">
					<input type="text" name="email_subject" id="email_subject" class="ipt f-left wp75"/>
					<div class="wp20 a-left">
						<a class="switch ml15 " href="javascript:switchSubject();" title="换一个">换</a>
						<a class="switch ml15" href="javascript:configSubject();" title="换一个">设置</a>
					</div>
					<div class="clr"></div>
				</div>
			</div>
		</div>
		<div class="email-content " style="padding-right:20px;">
			
			<textarea name="name" rows="20" id="email_body" name="email_body" style="width:90%;"></textarea>
			<script type="text/javascript">
			openEditorPopup = function(url, name, specs, parent) {
			    if ((typeof popups == "undefined") || popups[name] == undefined || popups[name].closed) {
			        if (typeof popups == "undefined") {
			            popups = new Array();
			        }
			        var opener = (parent != undefined ? parent : window);
			        popups[name] = opener.open(url, name, specs);
			    } else {
			        popups[name].focus();
			    }
			    return popups[name];
			}
			
			closeEditorPopup = function(name) {
			    if ((typeof popups != "undefined") && popups[name] != undefined && !popups[name].closed) {
			        popups[name].close();
			    }
			}
			</script>
			<script type="text/javascript">
				wysiwygemail_body = new tinyMceWysiwygSetup(
					"email_body", 
					{
						"enabled":true,
						"hidden":false,
						"use_container":false,
						"add_variables":false,
						"add_widgets":false,
						"no_display":false,
						"translator":{},
						"encode_directives":true,
						"directives_url":"<?php echo $this->getUrl('cms_wysiwyg/directive'); ?>",
						"popup_css":"<?php echo Mage::getBaseUrl('js')."/mage/adminhtml/wysiwyg/tiny_mce/themes/advanced/skedm/default/dialog.css"; ?>",
						"content_css":"<?php echo Mage::getBaseUrl('js')."/mage/adminhtml/wysiwyg/tiny_mce/themes/advanced/skedm/default/content.css"; ?>",
						"width":"100%",
						"plugedm":[],
						"directives_url_quoted":"<?php echo $this->getUrl('cms_wysiwyg/directive'); ?>",
						"add_images":true,
						"files_browser_window_url":"<?php echo $this->getUrl('cms_wysiwyg_images'); ?>",
						"files_browser_window_width":1000,
						"files_browser_window_height":400,
						"tab_id":"email_body",
						"widget_plugin_src":"<?php echo Mage::getBaseUrl('js')."/mage/adminhtml/wysiwyg/tiny_mce/plugedm/magentowidget/editor_plugin.js"; ?>",
						"widget_images_url":"http:\/\/kdd.com\/skin\/adminhtml\/default\/default\/images\/widget\/",
						"widget_placeholders":["catalog__category_widget_link.gif","catalog__product_widget_link.gif",
						"catalog__product_widget_new.gif","cms__widget_block.gif","cms__widget_page_link.gif",
						"default.gif",
						"reports__product_widget_compared.gif","reports__product_widget_viewed.gif"],
						"widget_window_url":"http:\/\/kdd.com\/index.php\/meegii\/widget\/index\/key\/358f59f7f17210b00440cee2ea666abe\/",
						"firebug_warning_title":"\u8b66\u544a",
						"firebug_warning_text":"Firebug is known to make the WYSIWYG editor slow unless it is turned off or configured properly.",
						"firebug_warning_anchor":"Hide"});
				Event.observe(window, "load", wysiwygemail_body.setup.bind(wysiwygemail_body, "exact"));
			    editorFormValidationHandler = wysiwygemail_body.onFormValidation.bind(wysiwygemail_body);
			    //registry 报错
			    //Event.observe("toggleemail_body", "click", wysiwygemail_body.toggle.bind(wysiwygemail_body));
			    varienGlobalEvents.attachEventHandler("formSubmit", editorFormValidationHandler);
			    varienGlobalEvents.attachEventHandler("tinymceBeforeSetContent", wysiwygemail_body.beforeSetContent.bind(wysiwygemail_body));
			    varienGlobalEvents.attachEventHandler("tinymceSaveContent", wysiwygemail_body.saveContent.bind(wysiwygemail_body));
			    varienGlobalEvents.clearEventHandlers("open_browser_callback");
			    varienGlobalEvents.attachEventHandler("open_browser_callback", wysiwygemail_body.openFileBrowser.bind(wysiwygemail_body)); 
			</script>
        </div>
        <div class="clr"></div>
        <div class="actions mt15">
        	<div class="f-left wp50">
        		
        	</div>
        	<div class="f-right wp50">
        		<button class="btn mb20 f-right" id="send_email_btn" type="submit" onclick="checkEmail()" style="">立即发送</button>
        	</div>
        	<div class="clr"></div>
        	<div id="send_email_loading" class=" loading-txt" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/loading_32x32.gif'); ?>" />邮件正在发送中，请稍后...</div>
        </div>
	</div>
</div>

<script>
function saveasTemplateProcess() {
	//输入名称
	jQuery('#lbme .lbme-h').html("存为模版");
	jQuery('#lbme .inner').html('<p>请输入模版名称，便于记忆<p><p><input type="text" class="ipt wp50" name="template_name" id="template_name"/></p><p><button class="btn" onclick="saveasTemplate();">确认 &amp; 保存</button>');
	jQuery('#lbme').lightbox_me({modalCSS: {top: '40%',width:'500px'}});

}
//存为模版
function saveasTemplate() {
	var template_name = jQuery('#template_name').val();
	var template_id = jQuery('#email_template').val();
	alert(template_name);
	if (template_name && template_id) {
		jQuery.post('<?php echo $this->getUrl('adminhtml/ajax_template/saveastemplate',array('isAjax'=>true)); ?>',{form_key:'<?php echo $this->getFormKey(); ?>',template_name:template_name,template_id:template_id},function(res) {
		  	if (res.ret==1) {
		  		//lightme 弹出层
		  		var myDate = new Date();
		  		jQuery('#lbme .inner').html("模版已于  "+myDate.getHours()+':'+myDate.getMinutes()+" 成功保存");
		  		jQuery('#lbme').lightbox_me({});
		  	} else {
		  		jQuery('#lbme .inner').html(res.msg);
		  		jQuery('#lbme').lightbox_me({});
		  		
		  	} 
		},'json')
	}
		
}
//标题设置
function configSubject() {
	var form_key = jQuery('#form_key').val();
	var module_name = "邮件标题";
	var cur_template = jQuery('#email_template').val();
	var client_id = jQuery('#client_id').val();
	var email_to = jQuery('#email_to').val();
	var email_subject = jQuery('#email_subject').val();
	var product_promo = jQuery('#keyword').val().trim();
	var config_url = jQuery('#config_url').val();
	jQuery.ajax({
		  url:config_url+'?module='+module_name+'&template='+cur_template,
		  data:{client_id:client_id,form_key:form_key,email:email_to,email_subject:email_subject,product_promo:product_promo},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  		
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
	             		var replaceStr = res.data;
	             		if (replaceStr) {
	             			
	             			jQuery('#lbme .lbme-h').html(module_name+' - 设置');
	             			jQuery('#lbme .inner').html(replaceStr);
							jQuery('#lbme').lightbox_me({});
	             		}
						
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
					}
		  	    } else {
		  	    	
		  	    }
		  }
	})
}

function saveModuleConfig(module_name) {
	var cur_template = jQuery('#email_template').val();
	var items = new Array();
	jQuery('.config-items input[name=item_id]:checked').each(function(){
		items.push(jQuery(this).val());
	})
	items = items.join(',');
	var config_save_url = jQuery('#config_save_url').val();
	var form_key = jQuery('#form_key').val();
	var module_id = jQuery('.config-items #module_id').val();
	jQuery.ajax({
		  url:config_save_url+'?module='+module_id+'&template='+cur_template,
		  data:{form_key:form_key,items:items},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  		
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
	             		var replaceStr = res.data;
	             		if (replaceStr) {
	             			
	             			jQuery('#lbme .lbme-h').html(module_name+' - 设置');
	             			jQuery('#lbme .inner').html('保存成功');
							jQuery('#lbme').lightbox_me({});
	             		}
						
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
					}
		  	    } else {
		  	    	
		  	    }
		  }
	})
}
</script>
<div style="display:none;width:800px;" id="lbme" class="lbme">
	<div class="lbme-h">保存模版</div>
	<div class="inner"></div>
	<div class="close"><i></i></div>
</div>