<?php $company = Mage::registry('current_company'); ?>
<?php $user = Mage::getSingleton('admin/session')->getUser(); ?>

<div class="e-edit">
    <section class="col2 b-r wp40" id="col_url">
    	<div class="inner">
    		
	    	<div class="sch-box pr"  id="joystep_1">
	    		<div class="" id="sch_ctn_keyword">
		    		<input type="text" id="keyword" class="ipt" placeholder="输入推广的产品关键字" value="" onclick="chosenShow('keyword_ctn');" onblur="chosenHide('keyword_ctn');"/>
		    		<button type="button " id="sch_btn_keyword" class="btn pa">搜索</button>
		    		<span class="i-icon-delete"></span>
		    		<?php $urls = Mage::getResourceModel('edm/company_keyword_collection')
						->addFieldToFilter('company_id',$company->getId())
						->setPageSize(20)
						->setOrder('date_create','desc');	?>
					<div class="pa keyword-box a-left" id="keyword_ctn" style="display:none;">
						<h5>最近输入：</h5>
						<ul>
							<?php foreach ($urls as $_url): ?>
							<li class="k-item" onclick="chosenKeyword('keyword',this)"><?php echo $_url->getData('keyword'); ?></li>
							<?php endforeach; ?>
						</ul>
					</div>
				</div>
				<div class="clr"></div>
				<div class="a-left mt10 fs16">
					<input type="checkbox" name="check_days" id="check_days" class="mr5"/>
					<label for="check_days">不显示7日内已发送邮件客户</label>
					
				</div>
				<div class="" id="sch_ctn_url" style="display:none;">
					<input type="text" id="url" class="ipt" placeholder="输入推广的客户网址" value="" onclick="chosenShow('url_ctn');" onblur="chosenHide('url_ctn');"/>
		    		<button type="button " id="sch_btn" class="btn pa">搜索</button>
		    		<span class="i-icon-delete"></span>
		    		<?php $urls = Mage::getResourceModel('edm/company_keyword_collection')
						->addFieldToFilter('company_id',$company->getId())
						->setPageSize(20)
						->setOrder('date_create','desc');	?>
					<div class="pa keyword-box a-left" id="url_ctn" style="display:none;">
						<h5>最近输入：</h5>
						<ul>
							<?php foreach ($urls as $_url): ?>
							<li class="k-item" onclick="chosenKeyword('keyword',this)"><?php echo $_url->getData('url'); ?></li>
							<?php endforeach; ?>
						</ul>
					</div>
				
				</div>
	    	</div>
	    	<div id="sch-result">
	    		
	    	</div>
	    	<div id="sch_tips_keyword" class="tips pr">
				<div style="padding:100px;font-size:26px;line-height: 40px;">输入推广的产品关键字</div>
			</div>
			<div id="sch_tips" class="tips" style="display:none;">
				<div style="padding:100px;font-size:26px;line-height: 40px;">输入推广客户网址</div>
			</div>
    	</div>
    </section>
    <section class="col2 email-main wp60" id="col_email">
    	<?php echo $this->getEditor(); ?>
    </section>
</div>
<script>
jQuery(function() {
	jQuery(document).ajaxStart(function(res){
		
	}).ajaxSuccess(function(res){
		
	}) 
})
function toggleModel(mode) {
	var targetBody = jQuery('#email_body_ifr').contents().find('#tinymce');
	if (mode==0) {
		
		targetBody.addClass('highlight');
		jQuery('#mode-highlight').addClass('active');
		jQuery('#mode-highlight').siblings().removeClass('active');
	} else if (mode==1) {
		targetBody.removeClass('highlight');
		jQuery('#mode-preview').addClass('active');
		jQuery('#mode-preview').siblings().removeClass('active');
	}
}
//根据网址，分析客户
function analysisByUrl(url,needWhois) {
	//选从数据库里查找，存在则不在查找
	if (needWhois) {
		setTimeout("searchWhois('"+url+"')",2000);
	}
	jQuery('#analysis_map').show().html('<div class="load"><img src="<?php echo $this->getSkinUrl("images/loading2.gif"); ?>" width="100%"/></div>"');
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/ajax_client/url',array('isAjax'=>true)); ?>',
		  data:{url:url,form_key:'<?php echo $this->getFormKey(); ?>'},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  	    res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
			  	    
				  	if (res.ret==1) {
						if (res.data) {
							jQuery('#analysis_map').html(res.data);
						} else {
							jQuery('#analysis_map').html('<p style="padding:50px;font-size:18px">对不起，由于网络原因，分析不成功。请重试或提交反馈给我们</p>');
						}
				  		
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
						getAnalysisProcess();
						
					}
		  	    } else {
		  	    	getAnalysisProcess();
		  	    	//setInterval(getAnalysisProcess,2000);
		  	    }
			  	    
		  }
	})

}
function searchWhois(url) {
	jQuery.ajax({
			  url:'<?php echo $this->getUrl('adminhtml/ajax_client/whois',array('isAjax'=>true)); ?>',
			  data:{url:url,form_key:'<?php echo $this->getFormKey(); ?>'},
			  timeout:20000,
			  dataType:"json",
			  complete:function(resp) { 
			  }
		})
}

/******************************************** 关键字搜索 start *********************************************************/
jQuery('#sch_btn_keyword').click(function(){
	searchKeyword();
})
function searchKeyword() {
	var q = jQuery('#keyword').val().trim();
	if (!q || q.length<3) {
		return;
	}
	jQuery('#sch_tips_keyword').html('<div class="load"><img src="<?php echo $this->getSkinUrl("images/loading2.gif"); ?>" width="100%"/></div>"');
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/ajax_analysis/keyword',array('isAjax'=>true)); ?>',
		  data:{q:q,form_key:'<?php echo $this->getFormKey(); ?>'},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  	    res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
						if (res.data) {
							jQuery('#sch_tips_keyword').html(res.data);
						} else {
							jQuery('#sch_tips_keyword').html('<p style="padding:50px;font-size:18px">对不起，由于网络原因，分析不成功。请重试或提交反馈给我们</p>');
						}
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}	
					}
		  	    } else {
		  	    	alert("分析出错，请重试或提交反馈信息，帮助我们不断提高服务质量")
		  	    }
			  	    
		  }
	})
}
/******************************************** 关键字搜索 end *********************************************************/
function getAnalysisProcess(last) {
	var url = jQuery('#keyword').val();
	jQuery.ajax({
		url:'<?php echo $this->getUrl('adminhtml/ajax_client/url',array('isAjax'=>true)); ?>',
		data:{url:url,form_key:'<?php echo $this->getFormKey(); ?>'},
	    timeout:40000,
	    dataType:"json",
	    complete:function(resp) {
  			res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
				  		console.log(res.data);
				  		
						jQuery('#sch_tips').html(res.data);
						
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
						if (!last) {
							getAnalysisProcess(1);
						}
					}
		  	    } else {
		  	    	if (!last) {
						getAnalysisProcess(1);
					}
		  	    }
		  }
	})
}

jQuery('#companyForm').submit(function(){
	jQuery.post(jQuery(this).attr('action'),jQuery('#companyForm').serialize(),function(res){
		if (res.ret==1) {
			alert('保存成功');
		} else {
			alert('res.msg');
		}
	},'json')
	
	return false;
})
jQuery(function(){
	
	jQuery('#emailPreview').click(function(){
		var email_to = jQuery('#email_to').val();
		var email_subject = jQuery('#email_subject').val();
		if (!email_subject) {
			alert("请填写邮件主题");
			return;
		}
		var url = jQuery(this).attr('data-url')+'?tid=4&subject='+email_subject;
		window.open(url);
	})
})
function chosenShow(target) {
	jQuery('#'+target).show();
}
function chosenHide(target) {
	jQuery('#'+target).fadeOut();
}
function chosenKeyword(target,e) {
	jQuery('#'+target).val(jQuery(e).text());
	jQuery(e).parents('.keyword-box').hide();
}
function renderEmail() {
	//summary 左移
	jQuery('.analysis_map').css('right',0);
	var email = jQuery('input[name=client_email]:checked').length > 0 ? jQuery('input[name=client_email]:checked').val() : '';
	var product_promo = jQuery('#keyword').val().trim();
	var template_id = jQuery('#email_template').val();
	product_promo = product_promo.replace(/,/g,";");
	//渲染内容
	var url = jQuery('#keyword').val();
	if (jQuery('#email_product').length) {
		jQuery('#email_product').val(product_promo);
	}
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/ajax_client/getmail',array('isAjax'=>true)); ?>',
		  data:{url:url,form_key:'<?php echo $this->getFormKey(); ?>',template_id:template_id,email:email,product_promo:product_promo},
		  timeout:20000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
						$this = jQuery(res.data);
						
						jQuery('#client_id').val(res.client_id);
						jQuery('#email_body').text($this.find('#email_body').text());
						//console.log($this.find('#module_handle_script').html());
						jQuery('#email_body_ifr').contents().find('#tinymce').html($this.find('#email_body').text());
						
						jQuery('#email_subject').val($this.find('#email_subject').val());
						jQuery('#email_to').val($this.find('#email_to').val());
						window.wysiwygemail_body.toggle();
						window.wysiwygemail_body.toggle();
						toggleModel(0);
						//console.log(jQuery('#email_body_ifr').contents().find('head'));
						//jQuery('#email_body_ifr').contents().find('head').append("<script src='<?php echo $this->getSkinUrl('template.js'); ?>'><\/script>");
						
						jQuery('#email_body_ifr').contents().find('#tinymce').append('#####################');
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
					}
		  	    } else {
		  	    	
		  	    }
		  }
	})
}


function renderEmailTest() {
	//summary 左移
	//jQuery('.analysis_map').css('right',0);
	var email = 'yanggaojiao@qq.com';
	var product_promo = 'Stone Sinks';
	product_promo = 'Stone Sinks';
	//渲染内容
	var template_id = jQuery('#email_template').val();
	var url = 'www.vesselsinks.com';
	
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/ajax_client/getmail',array('isAjax'=>true)); ?>',
		  data:{url:url,form_key:'<?php echo $this->getFormKey(); ?>',template_id:template_id,email:email,product_promo:product_promo},
		  timeout:20000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
						$this = jQuery(res.data);
						
						jQuery('#client_id').val(res.client_id);
						jQuery('#email_body').text($this.find('#email_body').text());
						//console.log($this.find('#module_handle_script').html());
						jQuery('#email_body_ifr').contents().find('#tinymce').html($this.find('#email_body').text());
						
						jQuery('#email_subject').val($this.find('#email_subject').val());
						jQuery('#email_to').val($this.find('#email_to').val());
						window.wysiwygemail_body.toggle();
						window.wysiwygemail_body.toggle();
						toggleModel(0);
						//console.log(jQuery('#email_body_ifr').contents().find('head'));
						//jQuery('#email_body_ifr').contents().find('head').append("<script src='<?php echo $this->getSkinUrl('template.js'); ?>'><\/script>");
						
						jQuery('#email_body_ifr').contents().find('#tinymce').append('#####################');
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
					}
		  	    } else {
		  	    	
		  	    }
		  }
	})
}
renderEmailTest();
function moduleHandle() {
	jQuery('.module_handle').mouseover(function(){
		alert('aa');
		jQuery(this).addClass('over')
	}).mouseout(function(){
		jQuery(this).removeClass('over')
	})
}

function sendEmail() {
	var email_to = jQuery('#email_to').val();
	var email_from = jQuery('#email_from').attr('data');
	var email_subject = jQuery('#email_subject').val();
	var email_body = jQuery('#email_body').text();
	var email_from_name = jQuery('#email_from').attr('data-from');
	var cc_me = jQuery("#cc_me").attr("checked")=="checked" ? 1 : 0;
	jQuery('#send_email_btn').attr('disabled','disabled');
	jQuery('#send_email_loading').show();
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/ajax_client/sendmail',array('isAjax'=>true)); ?>',
		  data:{email_to:email_to,form_key:'<?php echo $this->getFormKey(); ?>',email_from:email_from,email_subject:email_subject,email_body:email_body,cc_me:cc_me},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
				  		alert("恭喜您，邮件已经发送成功，请敬请等待客户的回复。")
				  	} else {
				  		if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
				  	}
		  	    }
		  	    jQuery('#send_email_loading').hide();
		  	    jQuery('#send_email_btn').removeAttr('disabled');
		  }
	})
	
}

function checkEmail() {
	var email_to = jQuery('#email_to').val();
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/ajax_client/checksend',array('isAjax'=>true)); ?>',
		  data:{email_to:email_to,form_key:'<?php echo $this->getFormKey(); ?>'},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==0) {
				  		if (confirm('您最近已给该客户发送邮件，是否再发一封')) {
							sendEmail();
						}
				  	} else {
				  		if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
						sendEmail();
				  	}
		  	    }
		  	   
		  }
	})
	
}

function switchSubject() {
	var client_id = jQuery('#client_id').val();
	var email_to = jQuery('#email_to').val();
	var email_subject = jQuery('#email_subject').val();
	var product_promo = jQuery('#keyword').val().trim();
	var switch_url = jQuery('#switch_url').val();
	var template = jQuery('#email_template').val();
	jQuery.ajax({
		  url:switch_url+'?module=邮件标题',
		  data:{template:template,client_id:client_id,form_key:'<?php echo $this->getFormKey(); ?>',email:email_to,email_subject:email_subject,product_promo:product_promo},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1 && res.data) {
				  		$this = jQuery(res.data);
						jQuery('#email_subject').val($this.text());
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
					}
		  	    } else {
		  	    	
		  	    }
		  }
	})
}
</script>

<script>
jQuery(function(){
	resetSection();
	jQuery(window).resize(function() {
		resetSection();
	})
})
function resetSection() {
	var height = jQuery(window).height()-40;
	//jQuery('.e-edit > section').css({height:height+'px'})
}
</script>

<!-- 下面是向导  -->
<ol id="joyRideTipContent" style="display:none;">
  <li data-id="joystep_1" data-text="下一步" class="custom" data-options="">
    <h2>#1</h2>
    <p>输入客户网站，如 http://www.apple.com/，点击“分析”按钮</p>
  </li>
  <li data-id="joystep_2" data-button="下一步" data-options="tipLocation:top;tipAnimation:fade">
    <h2>#2</h2>
    <p>选择客户的产品，有助于提高开发信质量</p>
  </li>
  <li data-id="joystep_3" data-button="下一步" data-options="tipLocation:right">
    <h2>#3</h2>
    <p>输入贵公司要推广的产品.</p>
  </li>
  <li data-id="joystep_4" data-button="下一步" data-options="tipLocation:right">
    <h2>#4</h2>
    <p>选择收件人邮箱地址，如没有，请手工在右侧“发件人”一栏输入.</p>
  </li>
  <li data-id="joystep_5" data-button="前往设置帐号基本信息" data-options="tipLocation:right">
    <h2>#5</h2>
    <p>点“生成开发信”按钮，即可生成一封匹配的开发信。前往设置帐号基本信息，即可立即体验！</p>
  </li>
  <!--
  <li data-id="joystep_6" data-button="完成" data-options="">
    <h2>Step #6</h2>
    <p>点击邮件发送按钮完成工作，原来写一封高质量的开发信就这么简单.</p>
  </li>-->
  <li data-id="joystep_7" data-button="完成" data-options="">
    <h2>#6</h2>
    <p>点击“我的设置”，更改公司信息.</p>
  </li>
</ol>

<script>
jQuery(function(){
	var status = '<?php if(!$user->getData('status_guide_email') && !$_SESSION['status_guide_email']){ echo 0; }else { echo 1;} ?>';

	if (status=='0') {
		jQuery('#keyword').val('www.roomstogo.com');
		searchAgain();
	} else {
		<?php if ($url = $this->getRequest()->getParam('url')): ?>
		jQuery('#keyword').val('<?php echo $url; ?>');
		searchAgain();
		<?php endif; ?>
	}
	
})
function renderJoyride() {
	jQuery('#joyRideTipContent').joyride({
    	autoStart : true,
      	postStepCallback : function (index, tip) {
      		if (index==5) { 
      			//完成设置
      			jQuery.get('<?php echo $this->getUrl('adminhtml/ajax_guide/finishsearch',array('isAjax'=>true)); ?>',{form_key:'<?php echo $this->getFormKey(); ?>'},function(res){
         			
         		},'json')
      		}
    	},
    	modal:true,
    	expose: true
    });
}

</script>