<div id="messages">
	<?php echo $this->getMessagesBlock()->toHtml() ?>
</div>
<div class="dir-container">
    <div class="d-box">
    	<div class="h">
    		<div class="f-left title">
    			<h3 class="m0">文档目录</h3>
    		</div>
    		<div class="f-right actions">
        		
				<div class="btn-group2">
				  <button type="button" class="btn btn-default btn-create"><i class="fa fa-plus mr5"></i>创建文件夹</button>
				  <button type="button" class="btn btn-primary btn-upload"><i class="fa fa-upload mr5"></i>上传文件</button>
				  <button type="button" class="btn btn-default view-as-list"><i class="fa fa-list"></i></button>
				  <button type="button" class="btn btn-default view-as-grid"><i class="fa fa-th"></i></button>
				</div>
    		</div>
        	<div class="clr"></div>
    	</div>
    </div>    
   	<div class="d-box mt5 ">
    	<div class="h">
    		<div class="f-left actions">
				<div class="btn-group2">
				  <button type="button" class="btn btn-default btn-moveto"><i class="fa fa-sign-in mr5"></i>移动</button>
				  <button type="button" class="btn btn-default btn-delete"><i class="fa fa-remove mr5"></i>删除</button>
				  <button type="button" class="btn btn-default btn-rename"><i class="fa fa-edit mr5"></i>重命名</button>
				  <button type="button" id="btn-back" class="btn btn-default btn-back" style="display:none;"><i class="fa fa-mail-reply mr5"></i>返回上级目录</button>
				</div>
    		</div>
    		<div class="f-right actions">
        		
				
    		</div>
    		
        	<div class="clr"></div>
    	</div>
    </div> 
    <div class="d-box mt5 p0">
    	<div class="no-display">
    		<input type="hidden" id="dir_parent" name="dir_parent" value=""/>
    	</div>
    	<div id="dir_ctn" class="mb20">
	    	<?php echo $this->getGridHtml(); ?>
	    	<div class="clr "></div>
    	</div>
    	<div class="clr mt20"></div>

    </div>                       
</div>
