<?php
$company = Mage::registry('current_company');
$cats = Mage::getResourceModel('edm/company_category_collection')
				->addFieldToFilter('company_id',$company->getId());	
$cats->getSelect()->join(array('p'=>'edm_product_category'),'p.category_id=main_table.category_id',array('level','name'));
$catOldIds = array();
$catNames = array();
$subCatNames = array();
foreach ($cats as $_cat) {
	array_push($catOldIds,$_cat->getCategoryId());
	
	if ($_cat->getLevel()==1) {
		array_push($catNames,$_cat->getName());
	} else if ($_cat->getLevel()==2) {
		array_push($subCatNames,$_cat->getName());
	}
}

?>
<div class="c-box">
	<div class="content-header">
		<div class="f-right">
			<div class=" f-right">
		   		<button class="btn btn-primary f-left" id="save_email_btn" type="button" onclick="saveInfo()" style=""><i class="fa fa-save"></i>&nbsp;确认，继续</button>
		   		
		   		<div class="clr"></div>
		   	</div>
		</div>
		<h2 class="m0"><i class="fa fa-setting mr5"></i>行业和产品设置</h2>
		<div id="messages">
            <?php echo $this->getMessagesBlock()->toHtml() ?>
        </div>
	</div>
	<div class="p15">
		<form action="<?php echo $this->getUrl('*/*/savecat'); ?>" method="post" id="baseForm">
			<div class="box-inner cat-box">
	
	            <div class="entry-edit" style="">
	            	<div>
	                	<h5 class="mt0">已选中行业：</h5>
	                	<div id="cat_box_selected" class="cat-selected"><?php echo implode('; ',$catNames); ?></div>
	                	<h5 class="mt15">已选中产品：</h5>
	                	<div id="subcat_box_selected" class="cat-selected"><?php echo implode('; ',$subCatNames); ?></div>
	            	</div>
	                <div id="cat_ctn">
	                	
	                	
	                	<h3 class="mb10 mt25">选择您从事的行业：</h3>
	                	
	                	<div id="cat_box">
	                		<div class="inner">
		                    	<?php $collection = Mage::getResourceModel('edm/product_category_collection')
		                       			->addFieldToFilter('level',0)
		                       			->addFieldToFilter('status',1); ?>
		                    	<?php foreach ($collection as $_item): ?>
		                    	<dl>
		                    		<dt><?php echo $_item->getName(); ?></dt>
		                    		<?php foreach ($_item->getChildren() as $_child): ?>
	                       			<dd data="<?php echo $_child->getId(); ?>" class="select-category <?php if(in_array($_child->getId(),$catOldIds)): ?> selected <?php endif; ?>"><?php echo $_child->getName(); ?><i class="fa f-right fa-check-square-o"></i></dd>
	                       			<?php endforeach; ?>
		                    	</dl>
		                    	<?php endforeach; ?>
	                    	</div>
	                    	
	                    	<div class="clr"></div>

	                	</div>
	                </div>
	                <div id="subcat_ctn" style="display:none;">
	                	<h3 class="mb10 mt25">选择您从事的产品：</h3>
	                	<div id="subcat_box">
	                	
	                	</div>
	                </div>
				</div>
			</div>
		</form>
	</div>
	<div class="content-bottom">
    	<div class="text-center">
    		<button class="btn btn-primary btn-lg" id="select_category_btn" type="button" style=""><i class="fa fa-save"></i>&nbsp;确认，继续</button>
    		<button class="btn btn-primary btn-lg" id="select_product_btn" type="button" onclick="saveStep1()" style="display:none;"><i class="fa fa-save"></i>&nbsp;确认保存</button>
    	</div>
    	<div class="clr"></div>
	</div>
</div>
<script>
jQuery('.select-category').click(function() {
	jQuery(this).toggleClass('selected');
})
jQuery('#select_category_btn').click(function() {
	
	var idsArr = new Array();
	var nameArr = new Array();
	jQuery('.select-category.selected').each(function() {
		idsArr.push(jQuery(this).attr('data'));
		nameArr.push(jQuery(this).text())
	})
	if (idsArr.length==0){
		alert('请至少选择一个行业，允许多选。');
		return;
	}
	var ids = idsArr.join(',');
	
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/edm_setting_info/getsubcat'); ?>',
		  data:{ids:ids,form_key:'<?php echo $this->getFormKey(); ?>'},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  	    res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
			  	    	
				  	if (res.ret==1) {
				  		$('#select_category_btn').hide();
				  		$('#select_product_btn').show();
				  		jQuery('#cat_ctn').hide();
				  		jQuery('#subcat_ctn').show();
				  		jQuery('#cat_box_selected').html(nameArr.join(';  ')).show();
				  		jQuery('#subcat_box').html(res.data);
				  		jQuery('.select-category').click(function() {
							jQuery(this).toggleClass('selected');
						})
					} else {
						
					}
		  	    } else {
		  	    	
		  	    	
		  	    }
			  	    
		  }
	})
})
//提交到后台保存起来
function saveStep1() {
	var idsArr = new Array();
	jQuery('.select-category.selected').each(function() {
		idsArr.push(jQuery(this).attr('data'));
	})
	var ids = idsArr.join(',');
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/edm_setting_info/savecat'); ?>',
		  data:{ids:ids,form_key:'<?php echo $this->getFormKey(); ?>'},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  	    res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
				  		alert("保存成功");
				  		window.location.href = '<?php echo $this->getUrl('adminhtml/edm_setting_info/cat'); ?>';
				  		
					} else {
						alert(res.msg);
						window.location.href = '<?php echo $this->getUrl('adminhtml/edm_setting_info/cat'); ?>';
					}
		  	    } else {
		  	    	
		  	    	
		  	    }
			  	    
		  }
	})
}
</script>