<?php $company = Mage::registry('current_company'); ?>
<?php $user = Mage::getSingleton('admin/session')->getUser(); ?>
<div class="inner"  id="box_email">
	<input type="hidden" id="form_key" value="<?php echo $this->getFormKey(); ?>" />
	<input type="hidden" id="client_id" value="" />
	<input type="hidden" id="switch_url" value='<?php echo $this->getUrl('adminhtml/edm_ajax_email/switch',array('isAjax'=>true)); ?>' />
	<input type="hidden" id="config_url" value='<?php echo $this->getUrl('adminhtml/edm_ajax_email/config',array('isAjax'=>true)); ?>' />
	<input type="hidden" id="config_save_url" value='<?php echo $this->getUrl('adminhtml/edm_ajax_email/configsave',array('isAjax'=>true)); ?>' />
	<div class="">
    	<div class="field mb5">
    		<?php $template = Mage::registry('current_template'); ?>
    		<?php if(!$template || !$template->getData('is_system')): ?><!-- 是否系统模板 -->
			<label class="tit">选择模版：</label>
			<div class="multi fields">
				<div class="a-left">
					<?php $templates = Mage::getResourceModel('edm/company_template_collection')
						->addFieldToFilter('template_company',$company->getId()); ?>
					<select name="email_template" id="email_template" class="ipt wp75" onchange="renderEmail();">
					<?php foreach ($templates as $_template): ?>
						<option value="<?php echo $_template->getId(); ?>"><?php echo $_template->getData('template_name'); ?></option>
					<?php endforeach; ?>
					</select>
					
				</div>
				<div class="clr"></div>
			</div>
			<?php else: ?>
			<label class="tit">当前模版：</label>
			<div class="multi fields">
				<div class="no-display">
					<input type="hidden" name="email_template" data-system="1" id="email_template" value="<?php echo $template->getId(); ?>" />
					
				</div>
				<div class="a-left">
					<span><?php echo $template->getTemplateName(); ?></span>
					
				</div>
				<div class="clr"></div>
			</div>
			<?php endif; ?>
		</div>
    	<div class="field">
			<label class="tit">收件人：</label>
			<div class="multi fields">
				<div class="wp100">
					<input type="text" name="email_to" id="email_to" class="ipt wp75 f-left"/>
					<div class="wp20">
					
					</div>
					<div class="clr"></div>
				</div>
			</div>
		</div>
		<div class="field">
			<label class="tit">发件人：</label>
			<div class="selection fields a-left">
				<div class=" f-left mr10">
					<?php $defaultAccount = $this->getDefaultAccount(); ?>
					<div class="btn-group f-left mr5">
			  			<button type="button" class="btn btn-default">
			  				
			  				<?php if ($defaultAccount->getData('account_firstname') && $defaultAccount->getData('account_lastname')): ?>
			  				<?php echo $defaultAccount->getData('account_lastname'); ?>&nbsp;<?php echo $defaultAccount->getData('account_firstname'); ?>&lt;<?php echo $defaultAccount->getData('account_email'); ?>&gt;
			  				<?php else: ?>
			  				<?php echo $defaultAccount->getData('account_name'); ?>&nbsp;&lt;<?php echo $defaultAccount->getData('account_email'); ?>&gt;
			  				<?php endif; ?>
			  				
			  			</button>
			  			<?php $accountCollection = $this->getAccountCollection(); ?>
			  			<?php if (count($accountCollection)): ?>
			  			<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
						    <span class="caret"></span>
						  </button>
						
			  			 <ul class="dropdown-menu" role="menu">
			  			 	<?php foreach ($accountCollection as $account): ?>
						    <li id="mode-highlight" onclick="toggleModel(0)">
						    	<a href="javascript:;"><?php echo $defaultAccount->getData('account_lastname'); ?>&nbsp;<?php echo $defaultAccount->getData('account_firstname'); ?>&lt;<?php echo $defaultAccount->getData('account_email'); ?>&gt;</a>
					    	</li>
			    			<?php endforeach; ?>
						 </ul>
						 <?php endif; ?>
					</div>
				</div>
				<div class=" f-left">
					<div class="">
						<input type="checkbox" name="cc_me" id="cc_me" /> 给我CC
					</div>
				</div>
				<ul class="dropdown" style="display:none">
					<li></li>
				</ul>
				<div class="clr"></div>
			</div>
			
		</div>
		<div class="field mb15">
			<label class="tit">邮件主题：</label>
			<div class="fields">
				<div class="wp100">
					<input type="text" name="email_subject" id="email_subject" class="ipt f-left wp75"/>
					<div class="wp20 a-left">
						<a class="btn btn-default btn-sm ml5 f-left" href="javascript:switchSubject();"><i class="fa fa-refresh mr5"></i>刷新</a>
						<a class="btn btn-default btn-sm ml5 f-left" href="javascript:configSubject();"><i class="fa fa-cog mr5"></i>设置</a>
					</div>
					<div class="clr"></div>
				</div>
			</div>
		</div>
		<div class="field mb15">
			<label class="tit">邮件内容：</label>
			<div class="fields">
				<div class="email-content " style="padding-right:20px;">
					<div id="handle-tools-box" style="">
						<div class="handle-tools">
							<a href="#" title=""><i class="fa fa-refresh"></i>&nbsp;刷新</a>
							<a href="#" title=""><i class="fa fa-trash"></i>&nbsp;移除</a>
							<a href="#" title=""><i class="fa fa-cog"></i>&nbsp;设置</a>
						</div>
					</div>
		        	<div id="email_body">
						<h1>您好，</h1>
						<p>欢迎使用艾欧外贸云办公服务，做外贸在艾欧启航！</p>
					</div>
		        </div>
	        </div>
        </div>
        <div class="clr"></div>
        
	</div>
</div>
<script>
function saveasTemplateProcess() {
	//输入名称
	jQuery('#lbme .lbme-h').html("存为模版");
	jQuery('#lbme .inner').html('<p>请输入模版名称，便于记忆<p><p><input type="text" class="ipt wp50" name="template_name" id="template_name"/></p><p><button class="btn" onclick="saveasTemplate();">确认 &amp; 保存</button>');
	jQuery('#lbme').lightbox_me({modalCSS: {top: '40%',width:'500px'}});

}
//存为模版
function saveasTemplate() {
	var template_name = jQuery('#template_name').val();
	var template_id = jQuery('#email_template').val();
	alert(template_name);
	if (template_name && template_id) {
		jQuery.post('<?php echo $this->getUrl('adminhtml/edm_ajax_template/saveastemplate',array('isAjax'=>true)); ?>',{form_key:'<?php echo $this->getFormKey(); ?>',template_name:template_name,template_id:template_id},function(res) {
		  	if (res.ret==1) {
		  		//lightme 弹出层
		  		var myDate = new Date();
		  		jQuery('#lbme .inner').html("模版已于  "+myDate.getHours()+':'+myDate.getMinutes()+" 成功保存");
		  		jQuery('#lbme').lightbox_me({});
		  	} else {
		  		jQuery('#lbme .inner').html(res.msg);
		  		jQuery('#lbme').lightbox_me({});
		  		
		  	} 
		},'json')
	}
		
}
//标题设置
function configSubject() {
	var form_key = jQuery('#form_key').val();
	var module_name = "邮件标题";
	var cur_template = jQuery('#email_template').val();
	var client_id = jQuery('#client_id').val();
	var email_to = jQuery('#email_to').val();
	var email_subject = jQuery('#email_subject').val();
	var product_promo = jQuery('#keyword').val().trim();
	var config_url = jQuery('#config_url').val();
	jQuery.ajax({
		  url:config_url+'?module='+module_name+'&template='+cur_template,
		  data:{client_id:client_id,form_key:form_key,email:email_to,email_subject:email_subject,product_promo:product_promo},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  		
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
	             		var replaceStr = res.data;
	             		if (replaceStr) {
	             			
	             			jQuery('#lbme .lbme-h').html(module_name+' - 设置');
	             			jQuery('#lbme .inner').html(replaceStr);
							jQuery('#lbme').lightbox_me({});
	             		}
						
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
					}
		  	    } else {
		  	    	
		  	    }
		  }
	})
}

function saveModuleConfig(module_name) {
	var cur_template = jQuery('#email_template').val();
	var items = new Array();
	jQuery('.config-items input[name=item_id]:checked').each(function(){
		items.push(jQuery(this).val());
	})
	items = items.join(',');
	var config_save_url = jQuery('#config_save_url').val();
	var form_key = jQuery('#form_key').val();
	var module_id = jQuery('.config-items #module_id').val();
	jQuery.ajax({
		  url:config_save_url+'?module='+module_id+'&template='+cur_template,
		  data:{form_key:form_key,items:items},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  		
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
	             		var replaceStr = res.data;
	             		if (replaceStr) {
	             			
	             			jQuery('#lbme .lbme-h').html(module_name+' - 设置');
	             			jQuery('#lbme .inner').html('保存成功');
							jQuery('#lbme').lightbox_me({});
	             		}
						
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
					}
		  	    } else {
		  	    	
		  	    }
		  }
	})
}
</script>

<script>
function toggleModel(mode) {}
jQuery(function(){
	jQuery('#emailPreview').click(function(){
		var email_to = jQuery('#email_to').val();
		var email_subject = jQuery('#email_subject').val();
		if (!email_subject) {
			alert("请填写邮件主题");
			return;
		}
		var url = jQuery(this).attr('data-url')+'?tid=4&subject='+email_subject;
		window.open(url);
	})
	jQuery('#email_body .module_handle').mouseover(function(){
		
	}).mouseout(function(){
		
	})
})

function renderEmail() {
	//summary 左移
	jQuery('.analysis_map').css('right',0);
	var email = jQuery('input[name=client_email]:checked').length > 0 ? jQuery('input[name=client_email]:checked').val() : '';
	var product_promo = 'Phone';
	var template_id = jQuery('#email_template').val();
	var template_system = jQuery('#email_template').attr('data-system');
	template_system = template_system ? template_system : 0;
	product_promo = product_promo.replace(/,/g,";");
	//渲染内容
	var url = jQuery('#keyword').val();
	if (jQuery('#email_product').length) {
		jQuery('#email_product').val(product_promo);
	}
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/edm_send/render',array('isAjax'=>true)); ?>',
		  data:{url:url,form_key:'<?php echo $this->getFormKey(); ?>',template_id:template_id,email:email,template_system:template_system,product_promo:product_promo},
		  timeout:20000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
						$this = jQuery(res.data);
						jQuery('#client_id').val(res.client_id);
						jQuery('#email_body').html($this.find('#email_body').html());
						
						jQuery('#email_subject').val($this.find('#email_subject').val());
						jQuery('#email_to').val($this.find('#email_to').val());
						
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
					}
		  	    } else {}
		  }
	})
}
renderEmail();

function sendEmail() {
	var email_to = jQuery('#email_to').val();
	var email_from = jQuery('#email_from').attr('data');
	var email_subject = jQuery('#email_subject').val();
	var email_body = jQuery('.email_body').text();
	var email_from_name = jQuery('#email_from').attr('data-from');
	var cc_me = jQuery("#cc_me").attr("checked")=="checked" ? 1 : 0;
	jQuery('#preview_email_btn').attr('disabled','disabled');
	jQuery('#send_email_loading').show();
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/edm_ajax_email/sendmail',array('isAjax'=>true)); ?>',
		  data:{email_to:email_to,form_key:'<?php echo $this->getFormKey(); ?>',email_from:email_from,email_subject:email_subject,email_body:email_body,cc_me:cc_me},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
				  		alert("恭喜您，邮件已经发送成功，请敬请等待客户的回复。")
				  	} else {
				  		if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
				  	}
		  	    }
		  	    jQuery('#send_email_loading').hide();
		  	    jQuery('#preview_email_btn').removeAttr('disabled');
		  }
	})
	
}

function checkEmail() {
	var email_to = jQuery('#email_to').val();
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/edm_ajax_email/checksend',array('isAjax'=>true)); ?>',
		  data:{email_to:email_to,form_key:'<?php echo $this->getFormKey(); ?>'},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==0) {
				  		if (confirm('您最近已给该客户发送邮件，是否再发一封')) {
							sendEmail();
						}
				  	} else {
				  		if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
						sendEmail();
				  	}
		  	    }
		  	   
		  }
	})
	
}
//邮件预览，先保存草稿，再预览
function previewEmail() {
	var email_to = jQuery('#email_to').val();
	var email_from = jQuery('#email_from').attr('data');
	var email_subject = jQuery('#email_subject').val();
	var email_body = jQuery('#email_body').html();
	var email_from_name = jQuery('#email_from').attr('data-from');
	var cc_me = jQuery("#cc_me").attr("checked")=="checked" ? 1 : 0;
	jQuery('#preview_email_btn').attr('disabled','disabled');
	jQuery('#send_email_loading').show();
	jQuery.post('<?php echo $this->getUrl('adminhtml/edm_ajax_email/saveDraft',array('isAjax'=>true)); ?>',{email_to:email_to,form_key:'<?php echo $this->getFormKey(); ?>',email_from:email_from,email_subject:email_subject,email_body:email_body,cc_me:cc_me},function(res){
		if (res.ret==1) {
	  		//保存草稿成功，跳转到预览页面
	  		window.location.href = '<?php echo $this->getUrl('adminhtml/edm_email_preview/'); ?>?id='+res.data.draft_id;
	  	} else {
	  		if (res.hasOwnProperty('ajaxRedirect')) {
				window.location.href = res.ajaxRedirect;
			}
	  	}
	},'json');
	
}
function switchSubject() {
	var client_id = jQuery('#client_id').val();
	var email_to = jQuery('#email_to').val();
	var email_subject = jQuery('#email_subject').val();
	var product_promo = jQuery('#keyword').val().trim();
	var switch_url = jQuery('#switch_url').val();
	var template = jQuery('#email_template').val();
	jQuery.ajax({
		  url:switch_url+'?module=邮件标题',
		  data:{template:template,client_id:client_id,form_key:'<?php echo $this->getFormKey(); ?>',email:email_to,email_subject:email_subject,product_promo:product_promo},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1 && res.data) {
				  		$this = jQuery(res.data);
						jQuery('#email_subject').val($this.text());
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
					}
		  	    } else {
		  	    	
		  	    }
		  }
	})
}
</script>
<div style="display:none;width:800px;" id="lbme" class="lbme">
	<div class="lbme-h">保存模版</div>
	<div class="inner"></div>
	<div class="close"><i></i></div>
</div>