<div class="logo f-left">
	<a class="home" class="" href="javascript:;">IoeGo - 外贸云办公</a>
	<span class="cname"><?php echo Mage::registry('current_company')->getName(); ?></span>
</div>
<div class="f-right">
	<!--
	<p class="more">
		<a href="<?php echo $this->getUrl('adminhtml/account/'); ?>" title="系统试用说明">系统试用说明&nbsp;<i class="fa fa-question-circle-o" aria-hidden="true"></i></a> 
		<a href="<?php echo $this->getUrl('adminhtml/index/logout'); ?>" title="退出系统">退出系统</a> 
	<p>
	-->
	<ul class="nav-m nav-h ">
		<li><a href="<?php echo $this->getUrl('adminhtml/account/'); ?>"><img class="avatar mr5" src="<?php echo $this->getSkinUrl('images/avatar/avatar_l.png'); ?>" /><?php echo Mage::getSingleton('admin/session')->getUser()->getName(); ?></a></li>
		<li>
			<a href="">了解更多</a>
			<ul></ul>
		</li>
		
	</ul>
</div>
<div class="nav-bar f-right">
	<ul class="nav-m ">
		<li><a href=""><i class="fa fa-desktop mr5" aria-hidden="true"></i>工作台</a></li>
		<li>
			<a href=""><i class="fa fa-th mr5" aria-hidden="true"></i>应用</a>
			<?php echo $this->getMenuLevelFirst($this->getMenuArray()); ?>
		</li>
		<li><a href=""><i class="fa fa-cog mr5" aria-hidden="true"></i>系统设置</a></li>
	</ul>
	
</div>

<script>
jQuery('#nav > li').mouseover(function(){
	jQuery(this).addClass('over');
}).mouseout(function(){
	jQuery(this).removeClass('over');
})

</script>