<div class="navigation <?php echo $this->getClass(); ?> ">
	<div class="navigation-header">
		<?php $app = Mage::registry('current_app'); ?>
		<?php if ($app): ?>
    	<div class="app-name"><i class="fa fa-<?php echo $app->getCode(); ?> mr5"></i><?php echo $app->getName(); ?></div>
    	<?php else: ?>
    	<div class="app-name"><?php echo Mage::registry('current_user')->getName(); ?></div>
    	<div class="app-set"><a href="<?php echo $this->getUrl('adminhtml/account_setting/') ?>" class="btn-appset" id="navigation-appset">个人设置</a></div>
    	<?php endif; ?>
    </div>
    <div class="clr"></div>
	<?php echo $this->getMenuLevel($this->getMenuArray()); ?>
	<div class="clr"></div>

	<?php if (!Mage::registry('current_app')): ?>
	<ul class="navleft">
		<li class="line"></li>
		<li class="  level0 nolink"> <a href="javascript:;" class=""><span>企业链接</span></a>
		<li class="  level0 small"> <a href="http://ioe9.com/" class="" target="_blank"><span>Mio框架官网</span></a>
	</li>
	<?php endif; ?>
</div>

<script>
jQuery('#nav > li').mouseover(function(){
	jQuery(this).addClass('over');
}).mouseout(function(){
	jQuery(this).removeClass('over');
})
jQuery('.navleft > li.parent > a').click(function(){
	$(this).next().toggle();
})
</script>