<?php if ($this->displayNoscriptNotice()): ?>
    <noscript>
        <div class="noscript">
            <div class="noscript-inner">
                <p><strong><?php echo $this->__('JavaScript seems to be disabled in your browser.'); ?></strong></p>
                <p><?php echo $this->__('You must have JavaScript enabled in your browser to utilize the functionality of this website.'); ?></p>
            </div>
        </div>
    </noscript>
<?php endif; ?>
<?php if ($this->displayDemoNotice()): ?>
    <p class="demo-notice"><?php echo $this->__('This is a demo store. Any orders placed through this store will not be honored or fulfilled.') ?></p>
<?php endif; ?>
