<div class="dashboard-container ">
    
    <div class="d-box">
    	<div class="h">
    		<div class="f-left title">
    			<h3 class="m0"><i class="fa fa-bar-chart-o mr10" aria-hidden="true"></i>邮件发送统计</h3>
    		</div>
    		<div class="f-right actions">
        		<div class="btn-group">
				  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">全公司 <span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu" role="menu">
				  	
				    <li><a href="#">全公司</a></li>
				    <li><a href="#">我自己</a></li>
				  </ul>
				</div>
				<div class="btn-group">
				  <button type="button" class="btn btn-default">本周</button>
				  <button type="button" class="btn btn-default">本月</button>
				  <button type="button" class="btn btn-default">本季</button>
				  <button type="button" class="btn btn-default">本年</button>
				</div>
    		</div>
        	<div class="clr"></div>
    	</div>
    	<div class="inner mt15">
    		<p class="empty">暂无数据</p>
    		
    	</div>
    </div>
    <div class="d-box mt10">
    	<div class="h">
    		<div class="f-left title">
    			<h3 class="m0"><i class="fa fa-calendar-check-o mr10" aria-hidden="true"></i>邮件发送数据分析</h3>
    		</div>
    		<div class="f-right actions">
    			<div class="btn-group">
				  <button type="button" class="btn btn-default">本周</button>
				  <button type="button" class="btn btn-default">本月</button>
				  <button type="button" class="btn btn-default">本季</button>
				  <button type="button" class="btn btn-default">本年</button>
				</div>
			</div>
    		<div class="clr"></div>
		</div>
		<div class="inner mt15">
    		<p class="empty">暂无数据</p>
    		
    	</div>
	</div>
    <div class="d-box mt10">
    	<div class="h">
    		<div class="f-left title">
    			<h3 class="m0"><i class="fa fa-calendar-check-o mr10" aria-hidden="true"></i>最近营销活动</h3>
    		</div>
			<div class="f-right actions">
    			<div class="btn-group">
				  <button type="button" class="btn btn-default">全部</button>
				  <button type="button" class="btn btn-default">排队中</button>
				  <button type="button" class="btn btn-default">已发送</button>
				  <button type="button" class="btn btn-default">已归档</button>
				</div>
				
			</div>
    		<div class="clr"></div>
		</div>
		<div class="inner mt15">
    		<p class="empty">暂无数据</p>
    		
    	</div>
	</div>
	
	<div class="d-box mt10">
    	<div class="h">
    		<div class="f-left title">
    			<h3 class="m0"><i class="fa fa-calendar-check-o mr10" aria-hidden="true"></i>最近新增联系人列表</h3>
    		</div>
    		
    		<div class="clr"></div>
		</div>
		<div class="inner mt15">
    		<p class="empty">暂无数据</p>
    		
    	</div>
	</div>                             
</div>
