<?php
/**
 * Uploader template for Wysiwyg Images
 *
 * @see Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content_Uploader
 */
?>
<div id="<?php echo $this->getHtmlId() ?>" class="uploader">
    <div class="buttons">
        <div id="<?php echo $this->getHtmlId() ?>-edmtall-flash" style="display:none">
            <?php echo Mage::helper('media')->__('This content requires last version of Adobe Flash Player. <a href="%s">Get Flash</a>', 'http://www.adobe.com/go/getflash/') ?>
        </div>
    </div>
    <div class="clear"></div>
    <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template">
        <div id="{{id}}" class="file-row">
        <span class="file-info">{{name}} ({{size}})</span>
        <span class="delete-button"><?php echo $this->getDeleteButtonHtml() ?></span>
        <span class="progress-text"></span>
        <div class="clear"></div>
        </div>
    </div>
    <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template-progress">
        {{percent}}% {{uploaded}} / {{total}}
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
maxUploadFileSizeInBytes = <?php echo $this->getDataMaxSizeInBytes() ?>;
maxUploadFileSize = '<?php echo $this->getDataMaxSize() ?>';

<?php echo $this->getJsObjectName() ?> = new Flex.Uploader('<?php echo $this->getHtmlId() ?>', '<?php echo $this->getUploaderUrl('media/uploader.swf') ?>', <?php echo $this->getConfigJson() ?>);
<?php echo $this->getJsObjectName() ?>.onFilesComplete = function(completedFiles){
    completedFiles.each(function(file){
        <?php echo $this->getJsObjectName() ?>.removeFile(file.id);
    });
    MediabrowserInstance.handleUploadComplete();
}
// hide flash buttons
if ($('<?php echo $this->getHtmlId() ?>-flash') != undefined) {
    $('<?php echo $this->getHtmlId() ?>-flash').setStyle({float:'left'});
}
//]]>
</script>
