<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>找回密码 - 艾欧外贸云办公，值得您信赖的外贸在线办公平台！</title>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('css/login.css') ?>" media="all" />
	<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>jquery.min.js"></script>
	<link rel="icon" href="<?php echo MAGE_HOST . 'favicon.ico' ?>" type="image/x-icon"/>
	<link rel="shortcut icon" href="<?php echo MAGE_HOST . 'favicon.ico' ?>" type="image/x-icon"/>
</head>
<body id="page-login">
    <div class="login-container">
        <div class="login-box">
            <form method="post" action="" id="loginForm">
                <div class="login-form">
                    <div class="heading">
                    	<h2>找回密码 - 艾欧外贸云办公平台</h2>
                	</div>
                	<div class="c-box">
	                    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey(); ?>" />
	                    
	                    <div id="messages">
	                        <?php echo $this->getMessagesBlock()->toHtml(); ?>
	                    </div>
	                    <label>请输入注册邮箱</label>
	                    <div class="input-box forgot-password  mb15">
	                        <input type="text" id="email" name="email" value="" placeholder="邮箱地址" class="required-entry input-text forgot-password validate-email" />
	                    </div>
	                    <?php echo $this->getChildHtml('form.additional.info'); ?>
	                    <div class="clear"></div>
	                    <div class="form-buttons mb20">
	                        
	                        <button class="forgot-password form-button" type="submit"><span><span><span>取回密码</span></span></span></button>
	                    </div>
	                    <a class="left" href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/index/login', array('_nosecret' => true)) ?>">&lt;&lt返回登录 </a>
                		<div class="clr"></div>
                	</div>
                </div>
                <p class="legal">&copy;<?php echo date('Y') ?> All rights reserved 上海龙茧信息科技有限公司 | Powered by Mio</p>
            </form>
            <div class="bottom"></div>
            <script type="text/javascript">
            $(function(){
            	$('#loginForm').submit(function(){
            		//if ($('#email').val() && reg.test($('#email').val())) {
            		if ($('#email').val()) {
            			return true;
            		} else {
            			return false;
            		}
            	})
            })
            </script>
        </div>
    </div>
</body>
</html>

