<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>

<body id="html-body"<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : ''; ?>>
<?php echo $this->getChildHtml('notification_window'); ?>
<div class="wrapper beta-wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
        <div class="header">
            <?php echo $this->getChildHtml('header') ?>
        <div class="clear"></div>
            <?php echo $this->getChildHtml('menu') ?>
        </div>
       
        <div class="middle" id="anchor-content">
            <div id="page:main-container">
            <?php if($this->getChildHtml('right')): ?>
                <div class="columns <?php echo $this->getContainerCssClass() ?>">
                    <div class="side-col" id="page:right">
                        <?php echo $this->getChildHtml('left') ?>
                    </div>
                    <div class="main-col" id="content">
                        <div class="main-col-inner">
                           
                            <?php echo $this->getChildHtml('content') ?>
                        </div>
                    </div>
                </div>
            <?php else: ?>
                <?php echo $this->getChildHtml('content') ?>
            <?php endif; ?>
            </div>
        </div>
        <div class="footer">
            <?php echo $this->getChildHtml('footer') ?>
        </div>
    </div>
    <?php echo $this->getChildHtml('js') ?>
    <?php echo $this->getChildHtml('profiler') ?>
<div id="loading-mask" style="display:none">
    <p class="loader" id="loading_mask_loader"><img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('adminhtml')->__('Loading...')) ?>"/><br/><?php echo Mage::helper('adminhtml')->__('Please wait...') ?></p>
</div>

<?php echo $this->getChildHtml('before_body_end') ?>

</body>
</html>
