<div class="dashboard-container ">
    <div id="messages">
        <?php echo $this->getMessagesBlock()->toHtml() ?>
    </div>
    <div class="d-box">
    	<div class="h">
    		<div class="f-left title">
    			<h3 class="m0"><i class="fa fa-bar-chart-o mr10"></i>最近报告数据</h3>
    		</div>
    		<div class="f-right actions">
        		
				<div class="btn-group">
				  <button type="button" class="btn btn-default">提交给我</button>
				  <button type="button" class="btn btn-default">抄送给我</button>
				  <button type="button" class="btn btn-default">我提交的</button>
				</div>
    		</div>
        	<div class="clr"></div>
    	</div>
    	<div class="inner mt15">
    		<p class="empty">暂无数据</p>
    	</div>
    </div>                            
</div>
