<?php
$company = Mage::registry('current_company');
$cats = Mage::getResourceModel('edm/company_category_collection')
				->addFieldToFilter('company_id',$company->getId());
		
$catOldIds = array();
foreach ($cats as $_cat) {
	array_push($catOldIds,$_cat->getCategoryId());
}

?>
<div class="c-box">
	<div class="content-header">
		<h2 class="head-dashboard">我的设置</h2></td>
	</div>
		
		<form action="" method="post" id="companyForm">
		<div id="step_1">
			<h3>请完善公司和个人信息</h3>
			<div class="dashboard-container mb20 step-box">
				<input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
			    <table cellspacing="25" width="100%">
			        <tr>
			            
			            <td>
			                <div class="entry-edit" >
			                    
			                    <div style="margin:20px;">
			                       <ul class="mb15">
			                       	
			                       	<li>
			                       		<label class="mb5 f-fix">公司名称：</label>
			                       		<div class="clr"></div>
			                       		<input type="text" id="company_name" name="company[name]" value="<?php echo $company->getName(); ?>" class="required-entry input-text" placeholder="请填写英文名称，可能在您签名，或邮件中使用"/>
			                       	</li>
			                       </ul>
			                       <ul class="mb15">
			                       	
			                       	<li>
			                       		<label class="mb5 f-fix">联系人：</label>
			                       		<div class="clr"></div>
			                       		<input type="text" id="company_contact_person" name="company[contact_person]" value="<?php echo $company->getData('contact_person'); ?>" class="required-entry input-text" placeholder="填英文名称，可能在您签名，或邮件中使用"/>
			                       	</li>
			                       </ul>
			                       <ul class="mb15">
			                       	
			                       	<li>
			                       		<label class="mb5 f-fix">联系邮箱：</label>
			                       		<div class="clr"></div>
			                       		<input type="text" id="company_contact_email" name="company[contact_email]" value="<?php echo $company->getData('contact_email'); ?>" class="required-entry input-text" placeholder="填接受客户询盘的邮箱"/>
			                       	</li>
			                       </ul>
			                       <ul class="mb15">
			                       	
			                       	<li>
			                       		<label class="mb5 f-fix">公司网址：</label>
			                       		<div class="clr"></div>
			                       		<input type="text" id="company_website" name="company[website]" value="<?php echo $company->getData('website'); ?>" class="required-entry input-text" placeholder="贵司网址"/>
			                       	</li>
			                       </ul>
			                    </div>
			                    <div class="btn-box mt20 mb20">
		                    		<button class="button" type="button" id="select_category_btn" onclick="saveStep1();">保存基本信息</button>
		                    	</div>
			                </div>
			            </td>
			        </tr>
			    </table>
			</div>
		</div>
		</form>
		<div id="step_2">
			<h3>公司优势设置</h3>
			<div class="dashboard-container mb20 step-box">
			    <table cellspacing="25" width="100%">
			        <tr>
			            <td>
			                <div class="entry-edit" style="">
			                	<h2 class="mb30">将开发信成功率提高600%</h2>
								<p class="fs16">贵司在品质，设计，价格，服务等方面有何优势？是触动客户的关键。回答了客户为什么要同贵司合作的最为关键的问题？</p>
								<p class="fs16">总共有三十多个可能设计到的问题，我们给您提供了大神写的例句，供您参考。如果您现在忙，以后也可以在我的设置|公司优势设置里设置。</p>
			                 	<div class="btn-box mt30 mb30 a-right">
			                 		<button class="button wp25 f-right" type="button" id="" onclick="setLocation('')">马上设置</button>
		                    		<button class="button wp25 f-right mr20" type="button" id="" onclick="setLocation('')">先逛逛</button>
		                    		
		                    	</div>
			                 </div>
			            </td>
			        </tr>
			    </table>
			</div>
		</div>
            			
		<form style="display:none" action="<?php echo $this->getUrl('adminhtml/dashboard/saveadvantage')  ?>" method="post" id="advantageForm" enctype="multipart/form-data">
		<div id="step_3">
			<h3>挖掘您的公司优势</h3>
			<input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
			<div class="dashboard-container mb20 step-box">
			    <table cellspacing="25" width="100%">
			        <tr>
			            <td>
			                <div class="entry-edit" style="">
			                    <h4>选中您公司的优势项，并进一步提供细节</h4>
			                   <?php $advantages = Mage::getResourceModel('edm/company_advantage_collection'); ?>
				                    <?php $oldAdvantageArr = array(); ?>
				                    <?php $oldAdvantage = Mage::getResourceModel('edm/company_advantage_value_collection')
				                    	->addFieldToFilter('company_id',$company->getId())
				                    	->addFieldToFilter('value',array('notnull'=>true)); ?>
				                    
				                    <?php foreach ($oldAdvantage as $_old): ?>
				                    	<?php if (!array_key_exists($_old->getAdvantageId(),$oldAdvantageArr)): ?>
				                    		<?php $oldAdvantageArr[$_old->getAdvantageId()] = array($_old); ?>
				                    		<?php else: ?>
				                    		<?php array_push($oldAdvantageArr[$_old->getAdvantageId()],$_old); ?>
				                    		<?php endif; ?>
				                    	
				                    <?php endforeach; ?>
				                    <?php foreach ($advantages as $_item): ?>
				                    	<?php $_item['enable_image'] = 0; ?>
					                    <div class="adv-item mb15">
					                    	<p><!--<input type="checkbox" name="advantage[<?php echo $_item->getId(); ?>]" value="1" class="mr5" />--><?php echo $_item->getName(); ?></p>
					                    	<div class="adv-inner pr">
					                    		<?php if ($_item->getData('advantage_type')=="text"): ?>
					                    			<?php if (array_key_exists($_item->getId(),$oldAdvantageArr)): ?>
					                    			<?php foreach ($oldAdvantageArr[$_item->getId()] as $_t): ?>
						                    		<div class="wr pr"><input type="text" value="<?php echo $_t->getValue(); ?>" name="advantage[<?php echo $_item->getId(); ?>][]" class="required-entry input-text wp80 mb5"/><button class="button" type="button" onclick="removeAdvantageItem(this);">删除</button></div>
						                    
						                    		<?php endforeach; ?>
						                    		<?php endif; ?>
						                    		<div class="wr pr"><input data-optional="<?php echo $_item->getData('optional_content'); ?>" type="text" placeholder="<?php echo $_item->getData('tips'); ?>" name="advantage[<?php echo $_item->getId(); ?>][]" value="" class="required-entry input-text wp80 mb5"/></div>
						                    		<?php if ($_item->getData('optional_content')): ?>
							                    		<div class="optional-box pa" style="display:none;">
							                    			<?php $optionalContent = explode("\n",trim($_item->getData('optional_content'))); ?>
							                    			<?php foreach ($optionalContent as $_oc) : ?>
							                    			
							                    			<p data-item="<?php echo $_item->getId(); ?>"><?php echo $_oc; ?></p>
							                    			<?php endforeach; ?>
							                    		</div>
						                    		<?php endif; ?>
						                    		<?php if ($_item['enable_image']): ?>
						                    		<button class="button adv-image-btn wp18 f-right" type="button" data-id="<?php echo $_item->getId(); ?>" data-target="adv_image_box_<?php echo $_item->getId(); ?>"> + 上传证书图片</button>
						                    		<?php endif; ?>
						                    		
					                    		<?php elseif ($_item->getData('advantage_type')=="multiselect" || $_item->getData('advantage_type')=="select"): ?>
					                    			<select data-placeholder="<?php echo $_item->getData('tips'); ?>" class="wp80 select chosen-select" name="advantage[<?php echo $_item->getId(); ?>]" <?php if ($_item->getData('advantage_type')=="multiselect"): ?>multiple="multiple"<?php endif; ?>>
					                    				<option value=""> - 请选择 - </option>
					                    				<?php $options = $_item->getChildrenOption(); ?>
					                    				<?php foreach ($options as $_option): ?>
					                    				<?php if ($_option->getData('value')): ?>
					                    				<option value="<?php echo $_option->getData('value'); ?>"><?php echo $_option->getData('value'); ?></option>
					                    				<?php endif; ?>
					                    				<?php endforeach; ?>
					                    			
					                    			</select>
					                    		<?php elseif ($_item->getData('advantage_type')=="boolean"): ?>
				                    				<select class="wp80 select chosen-select" name="advantage[<?php echo $_item->getId(); ?>]" >
				                    					<?php $checked = false; ?>
				                    					<?php if (array_key_exists($_item->getId(),$oldAdvantageArr)): ?>
					                    				<?php foreach ($oldAdvantageArr[$_item->getId()] as $_t): ?>
					                    				<?php if ($_t->getValue()): ?>
					                    					
					                    				<?php $checked = true; ?>
					                    				<?php endif; ?>
					                    				<?php endforeach; ?>
					                    				<?php endif; ?>
				                    					<option value="">否</option>
				                    					<option value="1" <?php if ($checked): ?>selected="selected"<?php endif; ?>>是</option>
				                    				</select>
					                    		<?php endif; ?>
					                    	</div>
					                    	<div class="clr"></div>
					                    	
					                    	<?php if ($_item['enable_image']): ?>
					                    	<div class="adv-image-box wp80 f-left mt5" id="adv_image_box_<?php echo $_item->getId(); ?>">
					                    		<ul>
					                    			<li class="mb5">
							                    		<input class="wp25" name="advantageimg[<?php echo $_item->getId(); ?>][image]" type="file" > 
							                    		<input class="required-entry input-text wp70 f-right" placeholder="请填写图片标题，以便于您管理" name="advantageimg[<?php echo $_item->getId(); ?>][title]" type="text">
							                    		<div class="clr"></div>
					                    			</li>
				                    			</ul>
					                    	</div>
					                    	<div class="clr"></div>
					                    	<?php endif; ?>
					                    </div>
					                    <div class="clr"></div>
				                    <?php endforeach; ?>
			                    
			                    <div class="btn-box mt20 mb20">
		                    		<button class="button" type="submit" id="select_advantage_btn" >完成&nbsp;&amp;&nbsp;提交</button>
		                    	</div>
			                </div>
			            </td>
			        </tr>
			    </table>
			</div>
		</div>
	</div>
	</form>
	<div class="no-display" id="adv_image_template">
    	<input class="wp25" name="advantageimg[templateid][image]" type="file"> 
		<input class="required-entry input-text wp70 f-right" placeholder="请填写图片标题，以便于您管理" name="advantageimg[templateid][title]" type="text">
		<div class="clr"></div>
    </div>
</div>
<script>



function saveStep1() {
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/ajax_guide/savecompany'); ?>',
		  //data:{ids:ids,form_key:'<?php echo $this->getFormKey(); ?>'},
		  data:jQuery('#companyForm').serialize(),
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  	    res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
				  		jQuery('#catForm').hide();
				  		jQuery('#companyForm').hide();
				  		jQuery('#advantageForm').show();
					} else {
						alert(res.msg);
					}
		  	    } else {
		  	    	
		  	    	
		  	    }
			  	    
		  }
	})
}
function saveStep2() {
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/ajax_guide/saveadvantage'); ?>',
		  data:jQuery('#advantageForm').serialize(),
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  	    res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
				  		
				  		
					} else {
						alert(res.msg);
					}
		  	    } else {
		  	    	
		  	    	
		  	    }
			  	    
		  }
	})
}
jQuery('.adv-image-btn').click(function(){
	var target = jQuery(this).attr('data-target');
	var str = jQuery('#adv_image_template').html().replace(/templateid/g,jQuery(this).attr('data-id'));
	jQuery('#'+target+' ul').append('<li class="mb5">'+str+'</li>');
	
})


jQuery(function(){
	jQuery(".chosen-select").chosen({disable_search_threshold: 10});
	jQuery(".adv-item .input-text").focus(function(){
		jQuery(this).parent().siblings('.optional-box').show();
	}).blur(function(){
		
		jQuery(this).parent().siblings('.optional-box').fadeOut();
	})
	jQuery('.adv-item .optional-box p').click(function(){
		var item_id = jQuery(this).attr('data-item');
		jQuery(this).parent().prev().before('<div class="wr pr"><input type="text" name="advantage['+item_id+'][]" value="'+jQuery(this).text()+'" class="required-entry input-text wp80 mb5"/><button class="button" type="button" onclick="removeAdvantageItem(this);">删除</button></div>');
		jQuery(this).parent().hide();
	})
	
})
function removeAdvantageItem(e) {
	jQuery(e).parent().remove();
}

</script>