<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard">我的工作面板</h3></td>
        </tr>
    </table>
</div>
<div class="dashboard-container">
    <table cellspacing="25" width="100%">
        <tr>
            
            <td>
                <div class="entry-edit" style="border:1px solid #ccc;">
                    
                    <div style="margin:20px;">
                        <?php //echo $this->getChildHtml('totals') ?>
                    </div>
                    <div style="margin:20px;">
                        <?php //echo $this->getChildHtml('grids') ?>
                        <div id="grid_tab_content"></div>
                    </div>
                </div>
            </td>
        </tr>
    </table>
</div>
