<div class="dashboard-container ">
    
    <div class="d-box">
    	<div class="h">
    		<div class="f-left title">
    			<h3 class="m0"><i class="fa fa-line-chart mr10"></i>数据看板</h3>
    		</div>
    		<div class="f-right actions">
        		<div class="btn-group">
				  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
				    CRM <span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu" role="menu">
				  	<?php $apps = Mage::getBlockSingleton('adminhtml/page_menu')->getApps(); ?>
					<?php foreach ($apps as $item): ?>
				    <li><a href="#"><?php echo $item['label']; ?></a></li>
				    <?php endforeach; ?>
				  </ul>
				</div>
				<div class="btn-group">
				  <button type="button" class="btn btn-default active">本周</button>
				  <button type="button" class="btn btn-default">本月</button>
				  <button type="button" class="btn btn-default">本季</button>
				  <button type="button" class="btn btn-default">本年</button>
				</div>
    		</div>
        	<div class="clr"></div>
    	</div>
    	<div class="inner mt15">
    		<p class="empty"><i class="fa fa-gg mr5"></i>暂未开放</p>
    		
    	</div>
    </div>
    <div class="d-box mt10">
    	<div class="h">
    		<div class="f-left title">
    			<h3 class="m0"><i class="fa fa-calendar-check-o mr10"></i>我的待办</h3>
    		</div>
    		<div class="clr"></div>
		</div>
		<div class="inner mt15">
    		<p class="empty"><i class="fa fa-gg mr5"></i>暂未开放</p>
    		
    	</div>
	</div>         
</div>
