<div class="chose-tree-wrap">
    <div class="chose-content clearfix" id="personAndDeptTree">
        <div class="tree-left-content">
            <div class="tree-wrapout">
                <div id="personTreeWrap">
                    <div class="tree-search-wrap clearfix">
                        <input name="personName" class="search float-l" type="text" placeholder="输入关键字" />
                        <i class="chose-person-icons tree-search-icon float-l"></i>
                    </div>
                    <div class="tree-wrapin" id="tree-scrollerbar" style="height: 264px;">
                        <div class="ztree tree-wrap" id="personTree">
                        </div>
                        <div class="data-wrap" style="display: none;">
                            <ul class="search-list">
                            </ul>
                        </div>
                    </div>
                </div>
                <div id="deptTreeWrap" style="display: none;">
                    <div class="tree-search-wrap clearfix">
                        <input name="deptName" class="search float-l" type="text" placeholder="输入关键字"/>
                        <i class="chose-person-icons tree-search-icon float-l"></i>
                    </div>
                    <div class="tree-wrapin" id="tree-scrollerbar">
                        <div class="ztree tree-wrap" id="deptTree">
                        </div>
                        <div class="data-wrap" style="display: none;">
                            <ul class="search-list">
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tree-gap">
            <i class="chose-person-icons tree-move-icon"></i>
        </div>
        <div class="tree-right-content">
            <div class="select-title-wrap">
                <p class="select-title">已选：人员（<span class="select-num-person">0</span>）</p>
            </div>
            <div class="select-wrap" id="selectWrap">
                <ul class="selected-ul" id="selected-list">
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-chose">
        <a href="javascript:;" class="chose-btn chose-confirm">确定</a>
        <a href="javascript:;" class="chose-btn chose-cancel">取消</a>
    </div>
</div>