<?php
$company = Mage::registry('current_company');
?>
<div class="c-box">
	<div class="content-header">
		<div class="f-right">
			<div class=" f-right">
		   		<button class="btn btn-info f-left mr10" id="" type="button" onclick="setLocation(window.location.href)"><i class="fa fa-refresh mr5"></i>重置</button>
		   		<button class="btn btn-primary f-left" id="" type="button" onclick="editForm.submit()" style=""><i class="fa fa-save mr5"></i>保存</button>
		   		
		   		<div class="clr"></div>
		   	</div>
		</div>
		<h2 class="m0"><i class="fa fa-edit mr5"></i>提交反馈</h2></td>
		
	</div>
	<form action="<?php echo $this->getUrl('*/*/save'); ?>" method="post" id="edit_form" enctype="multipart/form-data">
	
	<div class="p20">
		<div id="messages">
            <?php echo $this->getMessagesBlock()->toHtml() ?>
        </div>
        <div class="clr"></div>
        <div class="box-inner">
			<?php echo $this->getFormHtml(); ?>
		</div>
	</div>
	
	<div class="content-bottom text-center">
		<button class="btn btn-primary btn-lg w200" type="button" onclick="editForm.submit()" ><i class="fa fa-save mr5"></i>提交反馈信息</button>
    	<div class="clr"></div>
	</div>
	</form>
</div>
<script>
	editForm = new mioForm('edit_form','');
</script>