<?php
$company = Mage::registry('current_company');
?>
<div class="c-box">
	<div class="content-header">
		<h2 class="m0">提交反馈信息</h2></td>
		<div id="messages">
            <?php echo $this->getMessagesBlock()->toHtml() ?>
        </div>
	</div>
	<form action="<?php echo $this->getUrl('*/*/save'); ?>" method="post" id="feedbackForm" enctype="multipart/form-data">
	<input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
	<div class="p20">
		<div class="mb20 box-inner">
		  
            <div class="entry-edit" style="">
                <div style="margin:20px;" class="fieldset fieldset-wide">
               		<p style="color: #21b384; font-size: 20px; margin-top: -8px; margin-bottom: 22px;">您的宝贵意见和支持，是我们不断前进的动力。</p>
               		
               		<table class="form-list" cellspacing="0">
			            <tbody>
			                <tr>
						        <td class="label">
						        	<label for="title">标题</label>
					        	</td>
							    <td class="value">
							        <input id="title" name="title" value="" title="标题" class=" input-text" type="text" />
						        </td>
						    </tr>
							<tr>
						        <td class="label">
						        	<label for="feedback_content">反馈内容</label>
					        	</td>
							    <td class="value">
							        <textarea name="feedback_content" wrap="off" style="width:100%;height:180px;"></textarea>
						        </td>
						    </tr>
						    <tr>
						        <td class="label">
						        	<label for="image">上传截图</label>
					        	</td>
							    <td class="value">
							    	<input name="image" type="file" />
						        </td>
						    </tr>	
			            </tbody>
					</table>
		    		
                </div>
            </div>
		    
		</div>
	</div>
	
	<div class="content-bottom text-center">
		<button class="btn btn-primary btn-lg" type="submit" id="select_advantage_btn" >提交反馈信息</button>
    	<div class="clr"></div>
	</div>
	</form>
</div>
<script>

</script>