<footer class="footer">
	<div class="container">
    	<div class="footer_box" style="margin-right: 25px;">
        	<img src="<?php echo $this->getSkinUrl('images/logo_b.png'); ?>" />
        </div>
        <div class="footer_box">
        	<ul class="footer_menu">
            	<li><a href="#">关于我们</a></li>
                <li><a href="#">联系我们</a></li>
                <li><a href="#">加入我们</a></li>
                <li><a href="#">免责声明</a></li>
                <li><a href="#">捐赠我们</a></li>
            </ul>
        </div>
        <div class="footer_box">
        	<ul class="footer_menu">
                <li><a href="#">商务合作</a></li>
                <li><a href="#">合作伙伴</a></li>
                <li><a href="#">友情链接</a></li>
            </ul>
        </div>
        <div class="footer_box">
        	<ul class="footer_menu">
            	<li><a href="#">线下活动</a></li>
				<li><a href="#">技术讨论</a></li>
            </ul>
        </div>	
        <div class="footer_box">
        	<ul class="footer_menu">
            	<li><a href="#">RSS订阅</a></li>
                <li><a href="#">BUG反馈</a></li>
            </ul>
        </div>
        <div class="footer_box">
        	<p class="slogan">快来使用 MIO，激发你无限的洪荒之力！</p>

        </div>
        <div class="clr"></div>
        <div class="text-center copyright">
            <p>&copy <?php echo date('Y'); ?> All rights reserved. | Powered by Mio 1.0</p>
        </div>
        <div class="text-center gov">
        	
        </div>
    </div>
</footer>
