<?php $company = Mage::registry('current_company'); ?>
<?php $user = Mage::getSingleton('admin/session')->getUser(); ?>
<div class="inner"  id="box_email">
	<input type="hidden" id="form_key" value="<?php echo $this->getFormKey(); ?>" />
	<input type="hidden" id="client_id" value="" />
	<input type="hidden" id="switch_url" value='<?php echo $this->getUrl('adminhtml/ajax_client/switch',array('isAjax'=>true)); ?>' />
	<input type="hidden" id="config_url" value='<?php echo $this->getUrl('adminhtml/ajax_client/config',array('isAjax'=>true)); ?>' />
	<input type="hidden" id="config_save_url" value='<?php echo $this->getUrl('adminhtml/ajax_client/configsave',array('isAjax'=>true)); ?>' />
	<div class="">
    	<div class="field mb5">
			<label class="tit">选择模版：</label>
			<div class="multi fields">
				<div class="a-left">
					<?php $templates = Mage::getResourceModel('edm/company_template_collection')
						->addFieldToFilter('template_company',$company->getId()); ?>
					<select name="email_template" id="email_template" class="ipt wp75" onchange="renderEmail();">
					<?php foreach ($templates as $_template): ?>
						<option value="<?php echo $_template->getId(); ?>"><?php echo $_template->getData('template_name'); ?></option>
					<?php endforeach; ?>
					</select>
					
				</div>
				<div class="clr"></div>
			</div>
		</div>
    	<div class="field">
			<label class="tit">收件人：</label>
			<div class="multi fields">
				<div class="wp100">
					<input type="text" name="email_to" id="email_to" class="ipt wp75 f-left"/>
					<div class="wp20">
					
					</div>
					<div class="clr"></div>
				</div>
			</div>
		</div>
		<div class="field">
			<label class="tit">发件人：</label>
			<div class="selection fields a-left">
				<div class=" f-left mr10">
					<span class="selected" id="email_from" data-from="<?php echo $company->getData('contact_person') ?>" data="<?php echo $company->getData('contact_email') ?>"><?php echo $company->getData('contact_person') ?>&lt;<?php echo $company->getData('contact_email') ?>&gt;</span>
					<i class="icon icon-ad"></i>
				</div>
				<div class=" f-left">
					<div class="">
						<input type="checkbox" name="cc_me" id="cc_me" /> 给我CC
					</div>
				</div>
				<ul class="dropdown" style="display:none">
					<li></li>
				</ul>
				<div class="clr"></div>
			</div>
			
		</div>
		<div class="field mb15">
			<label class="tit">邮件主题：</label>
			<div class="fields">
				<div class="wp100">
					<input type="text" name="email_subject" id="email_subject" class="ipt f-left wp75"/>
					<div class="wp20 a-left">
						<a class="btn btn-default btn-sm ml5 f-left" href="javascript:switchSubject();"><i class="fa fa-refresh">刷新</i></a>
						<a class="btn btn-default btn-sm ml5 f-left" href="javascript:configSubject();"><i class="fa fa-cog">设置</i></a>
					</div>
					<div class="clr"></div>
				</div>
			</div>
		</div>
		<div class="field mb15">
			<label class="tit">邮件内容：</label>
			<div class="fields">
				<div class="email-content " style="padding-right:20px;">
					<div id="handle-tools-box" style="">
						<div class="handle-tools">
							<a href="#" title=""><i class="fa fa-refresh" aria-hidden="true"></i>&nbsp;刷新</a>
							<a href="#" title=""><i class="fa fa-trash" aria-hidden="true"></i>&nbsp;移除</a>
							<a href="#" title=""><i class="fa fa-cog" aria-hidden="true"></i>&nbsp;设置</a>
						</div>
					</div>
		        	<div id="email_body">
						<h1>Hello world!</h1>
						<p>Enjoy youself.</p>
					</div>
		        </div>
	        </div>
        </div>
        <div class="clr"></div>
        
	</div>
</div>
<script>
CKEDITOR.editorConfig = function( config ) {
	// The toolbar groups arrangement, optimized for two toolbar rows.
	config.toolbarGroups = [
		{ name: 'clipboard',   groups: [ 'clipboard', 'undo' ] },
		{ name: 'editing',     groups: [ 'find', 'selection', 'spellchecker' ] },
		{ name: 'links' },
		{ name: 'edmert' },
		{ name: 'forms' },
		{ name: 'tools' },
		{ name: 'document',	   groups: [ 'mode', 'document', 'doctools' ] },
		{ name: 'others' },
		'/',
		{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
		{ name: 'paragraph',   groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ] },
		{ name: 'styles' },
		{ name: 'colors' },
		{ name: 'about' }
	];

	// Remove some buttons provided by the standard plugedm, which are
	// not needed in the Standard(s) toolbar.
	config.removeButtons = 'Underline,Subscript,Superscript';

	// Set the most common block elements.
	config.format_tags = 'p;h1;h2;h3;pre';

	// Simplify the dialog windows.
	config.removeDialogTabs = 'image:advanced;link:advanced';
	config.allowedContent = true;
	config.extraAllowedContent = '*(*);*{*}';
};

/**
 * Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

/* exported initEditor */

if ( CKEDITOR.env.ie && CKEDITOR.env.version < 9 )
	CKEDITOR.tools.enableHtml5Elements( document );

// The trick to keep the editor in the sample quite small
// unless user specified own height.
CKEDITOR.config.height = 150;
CKEDITOR.config.width = 'auto';

var initEditor = ( function() {
	var wysiwygareaAvailable = isWysiwygareaAvailable(),
		isBBCodeBuiltIn = !!CKEDITOR.plugedm.get( 'bbcode' );

	return function() {
		var editorElement = CKEDITOR.document.getById( 'editor' );

		// :(((
		if ( isBBCodeBuiltIn ) {
			editorElement.setHtml(
				'Hello world!\n\n' +
				'I\'m an edmtance of [url=http://ckeditor.com]CKEditor[/url].'
			);
		}

		// Depending on the wysiwygare plugin availability initialize classic or inline editor.
		if ( wysiwygareaAvailable ) {
			CKEDITOR.replace( 'editor' );
		} else {
			editorElement.setAttribute( 'contenteditable', 'true' );
			CKEDITOR.inline( 'editor' );

			// TODO we can consider displaying some info box that
			// without wysiwygarea the classic editor may not work.
		}
	};

	function isWysiwygareaAvailable() {
		// If in development mode, then the wysiwygarea must be available.
		// Split REV into two strings so builder does not replace it :D.
		if ( CKEDITOR.revision == ( '%RE' + 'V%' ) ) {
			return true;
		}

		return !!CKEDITOR.plugedm.get( 'wysiwygarea' );
	}
} )();
initEditor();

</script>
<script>
function saveasTemplateProcess() {
	//输入名称
	jQuery('#lbme .lbme-h').html("存为模版");
	jQuery('#lbme .inner').html('<p>请输入模版名称，便于记忆<p><p><input type="text" class="ipt wp50" name="template_name" id="template_name"/></p><p><button class="btn" onclick="saveasTemplate();">确认 &amp; 保存</button>');
	jQuery('#lbme').lightbox_me({modalCSS: {top: '40%',width:'500px'}});

}
//存为模版
function saveasTemplate() {
	var template_name = jQuery('#template_name').val();
	var template_id = jQuery('#email_template').val();
	alert(template_name);
	if (template_name && template_id) {
		jQuery.post('<?php echo $this->getUrl('adminhtml/ajax_template/saveastemplate',array('isAjax'=>true)); ?>',{form_key:'<?php echo $this->getFormKey(); ?>',template_name:template_name,template_id:template_id},function(res) {
		  	if (res.ret==1) {
		  		//lightme 弹出层
		  		var myDate = new Date();
		  		jQuery('#lbme .inner').html("模版已于  "+myDate.getHours()+':'+myDate.getMinutes()+" 成功保存");
		  		jQuery('#lbme').lightbox_me({});
		  	} else {
		  		jQuery('#lbme .inner').html(res.msg);
		  		jQuery('#lbme').lightbox_me({});
		  		
		  	} 
		},'json')
	}
		
}
//标题设置
function configSubject() {
	var form_key = jQuery('#form_key').val();
	var module_name = "邮件标题";
	var cur_template = jQuery('#email_template').val();
	var client_id = jQuery('#client_id').val();
	var email_to = jQuery('#email_to').val();
	var email_subject = jQuery('#email_subject').val();
	var product_promo = jQuery('#keyword').val().trim();
	var config_url = jQuery('#config_url').val();
	jQuery.ajax({
		  url:config_url+'?module='+module_name+'&template='+cur_template,
		  data:{client_id:client_id,form_key:form_key,email:email_to,email_subject:email_subject,product_promo:product_promo},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  		
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
	             		var replaceStr = res.data;
	             		if (replaceStr) {
	             			
	             			jQuery('#lbme .lbme-h').html(module_name+' - 设置');
	             			jQuery('#lbme .inner').html(replaceStr);
							jQuery('#lbme').lightbox_me({});
	             		}
						
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
					}
		  	    } else {
		  	    	
		  	    }
		  }
	})
}

function saveModuleConfig(module_name) {
	var cur_template = jQuery('#email_template').val();
	var items = new Array();
	jQuery('.config-items input[name=item_id]:checked').each(function(){
		items.push(jQuery(this).val());
	})
	items = items.join(',');
	var config_save_url = jQuery('#config_save_url').val();
	var form_key = jQuery('#form_key').val();
	var module_id = jQuery('.config-items #module_id').val();
	jQuery.ajax({
		  url:config_save_url+'?module='+module_id+'&template='+cur_template,
		  data:{form_key:form_key,items:items},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  		
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
	             		var replaceStr = res.data;
	             		if (replaceStr) {
	             			
	             			jQuery('#lbme .lbme-h').html(module_name+' - 设置');
	             			jQuery('#lbme .inner').html('保存成功');
							jQuery('#lbme').lightbox_me({});
	             		}
						
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
					}
		  	    } else {
		  	    	
		  	    }
		  }
	})
}
</script>

<script>
function toggleModel(mode) {}
jQuery(function(){
	jQuery('#emailPreview').click(function(){
		var email_to = jQuery('#email_to').val();
		var email_subject = jQuery('#email_subject').val();
		if (!email_subject) {
			alert("请填写邮件主题");
			return;
		}
		var url = jQuery(this).attr('data-url')+'?tid=4&subject='+email_subject;
		window.open(url);
	})
	jQuery('#email_body .module_handle').mouseover(function(){
		
	}).mouseout(function(){
		
	})
})

function renderEmail() {
	//summary 左移
	jQuery('.analysis_map').css('right',0);
	var email = jQuery('input[name=client_email]:checked').length > 0 ? jQuery('input[name=client_email]:checked').val() : '';
	var product_promo = 'Phone';
	var template_id = jQuery('#email_template').val();
	product_promo = product_promo.replace(/,/g,";");
	//渲染内容
	var url = jQuery('#keyword').val();
	if (jQuery('#email_product').length) {
		jQuery('#email_product').val(product_promo);
	}
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/ajax_client/getmail',array('isAjax'=>true)); ?>',
		  data:{url:url,form_key:'<?php echo $this->getFormKey(); ?>',template_id:template_id,email:email,product_promo:product_promo},
		  timeout:20000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
						$this = jQuery(res.data);
						jQuery('#client_id').val(res.client_id);
						jQuery('#email_body').html($this.find('#email_body').html());
						//console.log($this.find('#email_body'));
						//CKEDITOR.edmtances['editor'].setData($this.find('#email_body').html());
						
						jQuery('#email_subject').val($this.find('#email_subject').val());
						jQuery('#email_to').val($this.find('#email_to').val());
						
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
					}
		  	    } else {}
		  }
	})
}
renderEmail();

function sendEmail() {
	var email_to = jQuery('#email_to').val();
	var email_from = jQuery('#email_from').attr('data');
	var email_subject = jQuery('#email_subject').val();
	var email_body = jQuery('.email_body').text();
	var email_from_name = jQuery('#email_from').attr('data-from');
	var cc_me = jQuery("#cc_me").attr("checked")=="checked" ? 1 : 0;
	jQuery('#preview_email_btn').attr('disabled','disabled');
	jQuery('#send_email_loading').show();
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/ajax_client/sendmail',array('isAjax'=>true)); ?>',
		  data:{email_to:email_to,form_key:'<?php echo $this->getFormKey(); ?>',email_from:email_from,email_subject:email_subject,email_body:email_body,cc_me:cc_me},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1) {
				  		alert("恭喜您，邮件已经发送成功，请敬请等待客户的回复。")
				  	} else {
				  		if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
				  	}
		  	    }
		  	    jQuery('#send_email_loading').hide();
		  	    jQuery('#preview_email_btn').removeAttr('disabled');
		  }
	})
	
}

function checkEmail() {
	var email_to = jQuery('#email_to').val();
	jQuery.ajax({
		  url:'<?php echo $this->getUrl('adminhtml/ajax_client/checksend',array('isAjax'=>true)); ?>',
		  data:{email_to:email_to,form_key:'<?php echo $this->getFormKey(); ?>'},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==0) {
				  		if (confirm('您最近已给该客户发送邮件，是否再发一封')) {
							sendEmail();
						}
				  	} else {
				  		if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
						sendEmail();
				  	}
		  	    }
		  	   
		  }
	})
	
}
//邮件预览，先保存草稿，再预览
function previewEmail() {
	var email_to = jQuery('#email_to').val();
	var email_from = jQuery('#email_from').attr('data');
	var email_subject = jQuery('#email_subject').val();
	var email_body = jQuery('#email_body').html();
	var email_from_name = jQuery('#email_from').attr('data-from');
	var cc_me = jQuery("#cc_me").attr("checked")=="checked" ? 1 : 0;
	jQuery('#preview_email_btn').attr('disabled','disabled');
	jQuery('#send_email_loading').show();
	jQuery.post('<?php echo $this->getUrl('adminhtml/ajax_client/saveDraft',array('isAjax'=>true)); ?>',{email_to:email_to,form_key:'<?php echo $this->getFormKey(); ?>',email_from:email_from,email_subject:email_subject,email_body:email_body,cc_me:cc_me},function(res){
		if (res.ret==1) {
	  		//保存草稿成功，跳转到预览页面
	  		window.location.href = '<?php echo $this->getUrl('adminhtml/email_preview/'); ?>?id='+res.data.draft_id;
	  	} else {
	  		if (res.hasOwnProperty('ajaxRedirect')) {
				window.location.href = res.ajaxRedirect;
			}
	  	}
	},'json');
	
}
function switchSubject() {
	var client_id = jQuery('#client_id').val();
	var email_to = jQuery('#email_to').val();
	var email_subject = jQuery('#email_subject').val();
	var product_promo = jQuery('#keyword').val().trim();
	var switch_url = jQuery('#switch_url').val();
	var template = jQuery('#email_template').val();
	jQuery.ajax({
		  url:switch_url+'?module=邮件标题',
		  data:{template:template,client_id:client_id,form_key:'<?php echo $this->getFormKey(); ?>',email:email_to,email_subject:email_subject,product_promo:product_promo},
		  timeout:120000,
		  dataType:"json",
		  complete:function(resp) {
		  		res = resp.responseText;
		  	    if (res) {
		  	    	res = JSON.parse(res);
				  	if (res.ret==1 && res.data) {
				  		$this = jQuery(res.data);
						jQuery('#email_subject').val($this.text());
					} else {
						if (res.hasOwnProperty('ajaxRedirect')) {
							window.location.href = res.ajaxRedirect;
						}
					}
		  	    } else {
		  	    	
		  	    }
		  }
	})
}
</script>
<div style="display:none;width:800px;" id="lbme" class="lbme">
	<div class="lbme-h">保存模版</div>
	<div class="inner"></div>
	<div class="close"><i></i></div>
</div>