<?php $items = $this->getCategoryCollection(); ?>
<div class="side-box">
	<div class="panel-heading">
	   	<h2 class="m0">标签云<span>Tags</span></h2>
		<div class="clr"></div>

	</div>
	<div class="mb20 p15 side-box-inner tags">
		<?php foreach ($items as $_item): ?>
			
			<a href="<?php echo $this->getUrl('adminhtml/college_article/list').'?id='.$_item->getId(); ?>" class="" title="<?php echo $_item->getName(); ?>"><?php echo $_item->getName(); ?></a>
		<?php endforeach; ?>
		<div class="clr"></div>
	</div>
	<div class="clr"></div>
</div>

<?php $items = $this->getWxCollection(); ?>
<div class="side-box">
	<div class="panel-heading">
	   	<h2 class="m0">热门公众号<span>Hot</span></h2>
		<div class="clr"></div>

	</div>
	<div class="mb20 p0 side-box-inner">
		<ul class="gbox m0">
			<?php $i = 0; ?>
			<?php foreach ($items as $_item): ?>
			<li class="gbox-i gbox-<?php echo $i; ?>">
				<?php $url = $this->getUrl('adminhtml/college_article/wx').'?id='.$_item->getId(); ?>
				<p><a class="" target="_blank" href="<?php echo $url; ?>" title="<?php echo $_item->getName(); ?>"><img src="<?php echo $_item->getImageUrl(); ?>" width="105" height="78" alt="<?php echo $_item->getName(); ?>"/></a></p>
				<h4><a class="" target="_blank" href="<?php echo $url; ?>" title="<?php echo $_item->getName(); ?>"><?php echo $_item->getName(); ?></a></h4>
			</li>
			<?php $i++; ?>
			<?php endforeach; ?>
			<li class="gbox-i gbox-100"><a class="btn btn-info btn-sm" target="_blank" href="">浏览更多公众号</a></a>
			</li>
		</ul>
		<div class="clr"></div>
	</div>
	<div class="clr"></div>
</div>