<div class="c-box f-left" style="height:700px">
	<div class="content-header">
		<div class="f-right">
			<div class=" f-right">
		   		<!--<button class="btn btn_grey f-left mr5" class="preview_email_btn" type="button" onclick="previewEmail()" style="">预览</button>-->
		   		<button class="btn btn-info f-left mr5" id="save_email_btn" type="button" onclick="saveasTemplateProcess()" style=""><i class="fa fa-save"></i>&nbsp;存为模版</button>
		   		<button class="btn btn-primary f-left mr5" id="send_email_btn" type="button" onclick="sendEmail()" style=""><i class="fa fa-send-o"></i>&nbsp;发送邮件</button>
		   		<div class="clr"></div>
		   	</div>
		</div>
	   	<h2 class="m0"><i class="fa fa-eye" aria-hidden="true"></i>&nbsp;邮件预览</h2>
		<div class="clr"></div>
		<div id="messages"></div>
	</div>
	<div class="mb20 p20 editor-box">
		<div id="email_body" style="height:600px">
			<?php $draft = Mage::registry('current_draft'); ?>
			<iframe src="<?php echo $this->getUrl('adminhtml/email_preview/draft'); ?>?id=<?php echo $draft->getId(); ?>" style="width: 100%; height: 500px;" class="cke_wysiwyg_frame cke_reset" title="所见即所得编辑器, editor" aria-describedby="cke_51" tabindex="0" allowtransparency="true" frameborder="0"></iframe>
		</div>
	</div>
</div>