<?php
/**
 * Template for Mage_Adminhtml_Block_Widget_Accordion
 */
?>
<dl id="tab_content_<?php echo $this->getHtmlId() ?>" name="tab_content_<?php echo $this->getHtmlId() ?>" class="accordion">
<?php foreach ($this->getItems() as $_item): ?>
    <?php echo $this->getChildHtml($_item->getId()) ?>
<?php endforeach ?>
</dl>
<script type="text/javascript">
    tab_content_<?php echo $this->getHtmlId() ?>AccordionJs = new varienAccordion('tab_content_<?php echo $this->getHtmlId() ?>', '<?php echo $this->getShowOnlyOne() ?>');
</script>
