<div class="side-widget">
	<a class="s01" href="#" target="_blank">
		<strong>吐血推荐</strong>
		<h2>外贸建站</h2>
		<p>专业的外贸公司官网和在线商城建站服务，拥有8年以上的跨境电商系统开发和运维经验，网址定制、快速仿站等专业服务，收费公道合理。</p>
	</a>
</div>
<div class="side-widget">
	<a class="s02" href="http://shang.qq.com/wpa/qunwpa?idkey=b876c6e625ab9c5efbdf6dd3f53d5caaf549ad1c4f0adce0099468efd4da70f4" target="_blank">
		<strong>加群啦</strong>
		<h2>IOEGO官方交流群</h2>
		<p>IOEGO官方交流群 群号：186058262，欢迎大家！ <br><img src="http://pub.idqqimg.com/wpa/images/group.png" alt="IOEGO官方交流群" title="IOEGO官方交流群" border="0"></p>
		</a>
</div>