<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3>
                  <?php if($this->getUser()->getUserId()): ?>
                  <?php $_userName = $this->getUser()->getFirstname() . ' ' . $this->getUser()->getLastname() ?>
                  <?php echo $this->__("Edit User '%s'", $_userName) ?>
                  <?php else: ?>
                  <?php echo $this->__('Add New User') ?>
                  <?php endif; ?>
                </h3>
            </td>
            <td class="form-buttons">
            <?php echo $this->getBackButtonHtml() ?>
            <?php echo $this->getResetButtonHtml() ?>
            <?php echo $this->getDeleteButtonHtml() ?>
            <?php echo $this->getSaveButtonHtml() ?>
   </table>
</div>
<form action="<?php echo $this->getUrl('*/*/saveuser') ?>" method="post" id="user_edit_form">
    <?php echo $this->getBlockHtml('formkey')?>
</form>
<script type="text/javascript">
    var userForm = new mioForm('user_edit_form');
</script>
